converter/src/main/java/gov/cms/qpp/conversion/model/error/Error.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/ValidationServiceImplTest.java
rest-api/src/test/resources/submissionDuplicateEntryErrorFixture.json

- QPPCT-395 kind of
- adjust for possibility of error details object rather than single entry array

QPPCT-395: aftermath

---

converter/src/test/java/gov/cms/qpp/conversion/model/error/ErrorTest.java

Make ErrorTest use junit 5

---

converter/src/test/java/gov/cms/qpp/conversion/model/error/AllErrorsTest.java

- JIRA story QPPCT-283.
- Updates a single class to use junit 5

Make AllErrorsTest use junit 5

---

rest-api/src/main/java/gov/cms/qpp/conversion/api/services/StorageServiceImpl.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/StorageServiceImplTest.java

- JIRA story QPPCT-482.
- We now SSE encrypt S3 uploads with the specified KMS key.

QPPCT-482: Encrypt S3 uploads with KMS key

---

pom.xml

- JIRA story QPPCT-468.
- This makes it so when tests fail, the exception stacktraces are not trimmed. Major help when debugging from console.

Disable stacktrace trimming in maven surefire

---

commandline/src/main/java/gov/cms/qpp/conversion/ConversionFileWriterWrapper.java

An enhancement.
- Removed extraneous `{}` since it wasn't being used.

Remove extraneous {} from conversion error

---

converter/src/test/java/gov/cms/qpp/acceptance/cpc/CpcPlusAcceptanceTest.java
pom.xml

- JIRA story QPPCT-522.
- Runs cpc+ acceptance tests using junit 5 parameterized tests, which nicely splits up test runs

Run cpc+ acceptance tests with junit 5 parameterized tests

---

.circleci/config.yml

- JIRA QPPCT-511
- Specified the use of a larger instance or resource class on which our build jobs should be executed.

QPPCT-511: use large instances to run build jobs

---

.circleci/config.yml

- JIRA story QPPCT-536.
- Lowers memory dedicated to the build through MAVEN_OPTS on circleci

Restrict memory usage with MAVEN_OPTS

---

converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
converter/src/test/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoderTest.java

- JIRA QPPCT-548
- use "group" as a stop gap entityType

QPPCT-548: use group instead of individual

---

.circleci/config.yml

- Enhancement PR
- Tells Maven to use 7 GB out of the available 8 GB in our CircleCI runs.

CircleCI builds use 7 GB

---

converter/src/main/java/gov/cms/qpp/conversion/decode/QppXmlDecoder.java
converter/src/main/java/gov/cms/qpp/conversion/encode/QppOutputEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/validate/NodeValidator.java
converter/src/test/java/gov/cms/qpp/conversion/validate/AggregateCountValidatorTest.java

- JIRA story QPPCT-414.
- While triaging calls to `new Reflections(...)` as per the QPPCT-414 description, I noticed that a lot of strings being creating at certain logger debug calls in high traffic methods.
- Due to the string concatenation in the logger debug statements, strings were being created even though debug logging was disabled.  Strings are now created only when debug logging is enabled.
- Deleted unused code from the debug logging refactor.
- Moved the memory expensive `XPathHelper#getAbsolutePath` call to below the `DecodeResult.TREE_ESCAPED` check.  This results in the call occurring only if the child node that was just decoded will stick around.

QPPCT-414: Reduced string creation rate

---

commandline/src/test/java/gov/cms/qpp/conversion/ConversionEntryTest.java

- Enhancement PR
- The log capturing wasn't working in IntelliJ, so changed the assertions to assert on something other than logs.

Don't use logging to assert functionality

---

converter/src/main/java/gov/cms/qpp/conversion/Converter.java
converter/src/main/java/gov/cms/qpp/conversion/encode/JsonWrapper.java
converter/src/test/java/gov/cms/qpp/conversion/ConversionReportTest.java
converter/src/test/java/gov/cms/qpp/conversion/encode/JsonWrapperTest.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/AuditServiceImpl.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/StorageService.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/StorageServiceImpl.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/AuditServiceImplTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/StorageServiceImplIntegration.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/StorageServiceImplTest.java

- JIRA story QPPCT-495.
- Uses the size specified in `Source` to specify the length to the `StorageService`.
- The warnings no longer appear and the log saying the S3 SDK will load the file into memory.
- Validated that the files are still uploaded correctly and not truncated.

QPPCT-495: Specify size for S3 uploads

---

converter/src/test/java/gov/cms/qpp/acceptance/SubmissionIntegrationTest.java
converter/src/test/java/gov/cms/qpp/conversion/encode/QualityMeasureIdMultiEncoderTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/AciMeasurePerformedRnRValidatorTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/AciSectionValidatorTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureIdValidatorTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/PerformanceRateValidatorTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/QualityMeasureSectionValidatorTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/ExceptionHandlerControllerV1Test.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/QrdaRestIntegration.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/AnyOrderAsyncActionServiceTest.java
rest-logging/src/test/java/gov/cms/qpp/conversion/logging/AttachmentHashPartConverterTest.java

- JIRA story QPPCT-283.
- Finishes the junit 5 conversion for all classes which do not need new code written. Still need to finish power mockito extension.

Finish junit 5 conversion (part 1 of 2)

---

.env
rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/CpcFileControllerV1.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Constants.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/CpcFileControllerV1Test.java

So... I jumped on this story early.  :)
- JIRA story QPPCT-563.
- "Created" the `NO_CPC_PLUS_API` environment variable.
- If it is set, we return a `403 Forbidden` from our CPC+ endpoints.

QPPCT-563: Add a new feature flag to our CPC+ Endpoints

---

converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java

- JIRA story QPPCT-562.
- Use US/Eastern ZoneId'd clock rather than UTC clock for validation

Use US/Eastern time instead of UTC

---

.circleci/config.yml

Fix-up task.
- Decreased Maven's memory footprint by another gigabyte because we are still getting Maven failures.

Maven runs in 6 GB on CircleCI

---

rest-api/src/main/java/gov/cms/qpp/conversion/api/services/DbServiceImpl.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/DbServiceImplTest.java

- QPPCT-598
- Change CPC+ endpoint 1 to have a max limit of up to 96 files that can be retrieved.

Limit DynamoDb retrieve file list

---

converter/src/main/java/gov/cms/qpp/conversion/encode/AciProportionDenominatorEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/encode/AciProportionNumeratorEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/encode/ClinicalDocumentEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/encode/IaMeasureEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/encode/JsonWrapper.java
converter/src/main/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/model/Node.java
converter/src/test/java/gov/cms/qpp/conversion/encode/AciProportionDenominatorEncoderTest.java
converter/src/test/java/gov/cms/qpp/conversion/encode/AciProportionNumeratorEncoderTest.java
converter/src/test/java/gov/cms/qpp/conversion/encode/JsonWrapperTest.java
converter/src/test/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoderTest.java
converter/src/test/java/gov/cms/qpp/conversion/model/NodeTest.java
sample-files/MIPS_GROUP_QRDA_III_ACI_IA_Sample2.xml

- QPPCT-629
- The assumption that some nodes have single entry child node lists resulted in the attempted encoding of incompatible nodes.

QPPCT-629: problem with only child assumption

---

commandline/src/test/java/gov/cms/qpp/conversion/ConverterWithAbridgedTest.java
converter/src/test/java/gov/cms/qpp/MarkupManipulationHandler.java
converter/src/test/java/gov/cms/qpp/acceptance/helper/JsonPathToXpathHelper.java
converter/src/test/java/gov/cms/qpp/acceptance/helper/MarkupManipulator.java
converter/src/test/java/gov/cms/qpp/conversion/model/RegistryTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/InOrderAsyncActionServiceTest.java

- JIRA story QPPCT-531.
- Removed extraneous uses of `System.out` and `System.err`.
- Changed a few instances where we printed something to an actual assert (`assertWithMessage`).
- In `JsonPathToXpathHelper`, we used to only check that all JSON paths, when mapped back to XPaths, didn't result in a `null` value in the original XML.  For certain attributes, we now check that the values are equal between the QPP and XML.

QPPCT-531: SPIKE - Investigate System.out/System.err printing in tests

---

converter/src/main/java/gov/cms/qpp/conversion/decode/QrdaDecoderEngine.java
converter/src/test/java/gov/cms/qpp/acceptance/ClinicalDocumentRoundTripTest.java
converter/src/test/java/gov/cms/qpp/conversion/decode/AggregateCountDecoderTest.java
converter/src/test/java/gov/cms/qpp/conversion/decode/QrdaDecoderEngineTest.java

- JIRA story QPPCT-655.
- Thanks to @clydet for the inspiration for this change!
- Filter out duplicate template IDs when decoding.
- This reduces the number of extraneous decoded `Node`s when a user accidentally includes extra `templateId` elements.
- A test.
- In the QRDA3 file attached to the original issue, it drops the number of issues from "holy cow, just start over on that file" to 2!

QPPCT-655: Filter out duplicate templateId elements

---

benchmark/pom.xml

- JIRA story QPPCT-651.
- The only issues with the benchmark sub-project were generated sources by JMH, not our own code.
- Told checkstyle to ignore the generated sources.

QPPCT-651: Active checkstyle on benchmark and ignore JMH generated sources

---

commons/src/main/java/gov/cms/qpp/conversion/util/EnvironmentHelper.java
converter/src/main/java/gov/cms/qpp/conversion/Context.java
converter/src/main/java/gov/cms/qpp/conversion/InputStreamSupplierSource.java
converter/src/main/java/gov/cms/qpp/conversion/correlation/PathCorrelator.java
converter/src/main/java/gov/cms/qpp/conversion/decode/AciProportionNumeratorDecoder.java
converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
converter/src/main/java/gov/cms/qpp/conversion/decode/IaSectionDecoder.java
converter/src/main/java/gov/cms/qpp/conversion/decode/MeasurePerformedDecoder.java
converter/src/main/java/gov/cms/qpp/conversion/decode/PerformanceRateProportionMeasureDecoder.java
converter/src/main/java/gov/cms/qpp/conversion/decode/QrdaDecoder.java
converter/src/main/java/gov/cms/qpp/conversion/decode/QrdaDecoderEngine.java
converter/src/main/java/gov/cms/qpp/conversion/decode/XmlDecoderEngine.java
converter/src/main/java/gov/cms/qpp/conversion/encode/ScopedQppOutputEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/model/Encoder.java
converter/src/main/java/gov/cms/qpp/conversion/model/Node.java
converter/src/main/java/gov/cms/qpp/conversion/model/Program.java
converter/src/main/java/gov/cms/qpp/conversion/model/Registry.java
converter/src/main/java/gov/cms/qpp/conversion/model/TemplateId.java
converter/src/main/java/gov/cms/qpp/conversion/model/error/Detail.java
converter/src/main/java/gov/cms/qpp/conversion/util/JsonHelper.java
converter/src/main/java/gov/cms/qpp/conversion/validate/Checker.java
converter/src/main/java/gov/cms/qpp/conversion/validate/ClinicalDocumentValidator.java
converter/src/main/java/gov/cms/qpp/conversion/validate/CpcMeasureDataValidator.java
converter/src/main/java/gov/cms/qpp/conversion/validate/MeasureDataValidator.java
converter/src/main/java/gov/cms/qpp/conversion/validate/MeasurePerformedValidator.java
converter/src/main/java/gov/cms/qpp/conversion/validate/MipsQualityMeasureIdValidator.java
converter/src/main/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidator.java
pom.xml
rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/QrdaControllerV1.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/helper/MetadataHelper.java

- QPPCT-681
- disabled generation of java documentation for private members

QPPCT-681: disable javadoc for private

---

rest-api/src/test/java/gov/cms/qpp/conversion/api/acceptance/CpcApiAcceptance.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/acceptance/QrdaApiAcceptance.java
test-commons/src/main/java/gov/cms/qpp/test/helper/AwsTestHelper.java

Fixes our acceptance tests in master.
- Forces us to use `us-east-1` with our acceptance tests since CircleCI doesn't know what region to use.  We were already forcing the region with other clients we were making in our acceptance tests, so now we are consistent.

Force to use us-east-1 for our acceptance tests

---

sonar-project.properties

- JIRA story QPPCT-642.
- Scan our `commons` project now.
- Tell Sonar that we are using Java 8 so it is smarter with its rules.
- Modified some of the Sonar rules that we use.

QPPCT-642: Update Sonar

---

converter/src/main/java/gov/cms/qpp/conversion/validate/MipsQualityMeasureIdValidator.java
converter/src/test/java/gov/cms/qpp/acceptance/QualityMeasureIdRoundTripTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidatorTest.java

- JIRA story QPPCT-693.
- Before, when the performance UUID was incorrect, we were generating an error message that stated the performance rate UUID needed to be what was already _provided_ in the QRDA3 file versus the _expected_ UUIDs.
- We now supply the expected UUIDs for the performance rate.

QPPCT-693: Error message for invalid performanceRateUuid is incorrect

---

commons/src/main/java/gov/cms/qpp/conversion/model/validation/SubPopulationLabel.java
commons/src/main/java/gov/cms/qpp/conversion/model/validation/SubPopulations.java
commons/src/main/java/gov/cms/qpp/conversion/util/StringHelper.java
commons/src/test/java/gov/cms/qpp/conversion/util/StringHelperTest.java
converter/src/main/java/gov/cms/qpp/conversion/encode/MeasureDataEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/validate/ClinicalDocumentValidator.java
converter/src/main/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureIdValidator.java
converter/src/main/java/gov/cms/qpp/conversion/validate/MipsQualityMeasureIdValidator.java
converter/src/main/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidator.java
converter/src/test/java/gov/cms/qpp/acceptance/MeasureDataRoundTripTest.java
converter/src/test/java/gov/cms/qpp/acceptance/QualityMeasureIdMultiRoundTripTest.java
converter/src/test/java/gov/cms/qpp/acceptance/cpc/CpcPlusAcceptanceTest.java
converter/src/test/java/gov/cms/qpp/conversion/decode/MeasureDataDecoderTest.java
converter/src/test/java/gov/cms/qpp/conversion/decode/QualityMeasureScopedTest.java
converter/src/test/java/gov/cms/qpp/conversion/encode/MeasureDataEncoderTest.java
converter/src/test/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoderTest.java
converter/src/test/java/gov/cms/qpp/conversion/encode/QualityMeasureIdMultiEncoderTest.java
converter/src/test/java/gov/cms/qpp/conversion/model/validation/SubPopulationsTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/CpcMeasureDataValidatorTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureScopedValidatonTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidatorTest.java
converter/src/test/resources/cpc_plus/failure/fixture.json
converter/src/test/resources/fixtures/qppct298/cms137v5_MissingMeasure.xml
generate/src/main/java/gov/cms/qpp/generator/QrdaGenerator.java

- QPPCT-685
- replaced string based subpopulation references with an enum type that allows aliasing.

QPPCT-685: ipp ipop support

---

commandline/src/main/java/gov/cms/qpp/conversion/CommandLineMain.java
commandline/src/main/java/gov/cms/qpp/conversion/CommandLineRunner.java
commandline/src/main/java/gov/cms/qpp/conversion/ConversionFileWriterWrapper.java
commandline/src/test/java/gov/cms/qpp/conversion/CommandLineMainTest.java
commandline/src/test/java/gov/cms/qpp/conversion/CommandLineRunnerTest.java

- JIRA story QPPCT-717.
- The regex for determining if a path is correct or not only allowed `/` separators.
- This has been changed to allow a path separator based on the supplied `FileSystem`.

QPPCT-717: Command line doesn't work on Windows

---

converter/src/main/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/util/MeasureConfigHelper.java
converter/src/main/java/gov/cms/qpp/conversion/validate/CpcMeasureDataValidator.java
converter/src/main/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureIdValidator.java
converter/src/main/java/gov/cms/qpp/conversion/validate/MipsQualityMeasureIdValidator.java
converter/src/main/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidator.java
converter/src/test/java/gov/cms/qpp/conversion/util/MeasureConfigHelperTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureIdValidatorTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidatorTest.java

- MeasureConfigHelper to extract the measure configuration from a node.
- Add new helper for measure configurations.
- Refactor validations to use the MeasureConfigHelper.
- Refactor MipsQualityMeasureValidator to remove additional configuration retrieval.

MeasureConfigHelper

---

commons/src/main/java/gov/cms/qpp/conversion/util/EnvironmentHelper.java
commons/src/test/java/gov/cms/qpp/conversion/util/EnvironmentHelperTest.java

- JIRA story QPPCT-709.
- Made isPresent and getOrDefault methods not print anything

Prevent log spam on isPresent and getOrDefault

---

DockerfileTest

- QPPCT-718
- Updates the docker file to be able to run on Docker-toolbox windows 7
- When I ran docker before the changes, I received the same error the user was getting.
- Unable to test on windows 10 as docker doesn't work on a windows vm. (Hyper V issues.)
- I excluded our main docker file because I doubt any users would be running our spunk in their docker.

Running Docker Compose on Windows

---

commandline/pom.xml

- JIRA story QPPCT-778.
- Replaces maven-assembly-plugin with maven-shade-plugin in the commandline module

Replace assembly with shade in commandline

---

.circleci/config.yml
frontend/src/app/app.component.ts
frontend/src/index.html
rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/CpcFileControllerV1.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/QrdaControllerV1.java
tools/bin/docker_deploy.sh

- JIRA story QPPCT-748.
- The SimpleUI sends in the `Purpose` header with `SimpleUI`.
- Reset the default `base href` to `/` and set it to `/developers/conversion-tool-sandbox/` only during deployment.
- Force `allowCredentials` to `true` for CORS since Spring 5.0 defaults to `false`.

QPPCT-748: SimpleUI sends Purpose header

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
commons/src/test/java/gov/cms/qpp/conversion/ErrorCodeTest.java

- JIRA story QPPCT-814.
- Added a test to enforce error code orders

Enforce error code ordering

---

converter/src/main/java/gov/cms/qpp/conversion/model/Node.java
converter/src/main/java/gov/cms/qpp/conversion/model/TemplateId.java
converter/src/main/java/gov/cms/qpp/conversion/model/error/Detail.java
converter/src/test/java/gov/cms/qpp/conversion/model/NodeTest.java
converter/src/test/java/gov/cms/qpp/conversion/model/TemplateIdTest.java
converter/src/test/java/gov/cms/qpp/conversion/model/error/DetailTest.java

- JIRA story QPPCT-762.
- Added another field to `Detail`, the class that gets serialized to report validation errors to our users, called `location`.
- That field holds a human readable location.
- Gave human readable titles to certain `TemplateId`s.
- When an validation error occurs, the first `Node` or its parent that contains a human readable `TemplateId` is searched for.  The subsequently created `Detail` fills this human readable title as the `location`.
- If this `Node` is a measure, the measure ID is obtained and appended to the human readable `location`.

QPPCT-762: Add better context to messages

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
converter/src/main/java/gov/cms/qpp/conversion/validate/PerformanceRateValidator.java
converter/src/test/java/gov/cms/qpp/acceptance/cpc/CpcPlusAcceptanceTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/PerformanceRateValidatorTest.java
converter/src/test/resources/cpc_plus/failure/fixture.json

- JIRA story QPPCT-810.
- Updated error code 33 to mention the supplied invalid value and specify the valid value range.
- Added the new error code 70 when the performance rate is missing.
- Did not add additional context to the error message because that'll be covered by #711.

QPPCT-810: Error message changes for 33

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/DocumentationReference.java
commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java

- QPPCT-836 and QPPCT-837
- CPC+ Performance period start and end error messages updated to reflect they are CPC+ submissions.
- Add a pointer to the IG for both errors.

Error messages 55 and 56 updates

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
converter/src/main/java/gov/cms/qpp/conversion/validate/CommonNumeratorDenominatorValidator.java
converter/src/test/java/gov/cms/qpp/conversion/validate/AciDenominatorValidatorTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/AciNumeratorValidatorTest.java

- QPPCT-827
- Removes error code 38 due to duplicate error messages
- Updates error code 39 with better messaging.

Remove error code 38 and update error code 39

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
converter/src/test/java/gov/cms/qpp/acceptance/CpcPlusRoundTripTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidatorTest.java

Now we don't want TIN in APM CPC+.

---

rest-api/src/main/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidator.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidatorTest.java

- Fix for NPE on CPC+ warning validation with invalid APM

fix npe when APM is invalid

---

converter/src/main/java/gov/cms/qpp/conversion/encode/ClinicalDocumentEncoder.java
converter/src/test/java/gov/cms/qpp/acceptance/CpcPlusRoundTripTest.java
converter/src/test/java/gov/cms/qpp/conversion/encode/ClinicalDocumentEncoderTest.java

- APM was encoding NPI's. Excluding NPI when it is an APM entity

Fix for APM entity encoding unwanted NPI's

---

converter/src/main/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoder.java
converter/src/test/java/gov/cms/qpp/acceptance/QualityMeasureIdRoundTripTest.java
converter/src/test/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoderTest.java
converter/src/test/resources/negative/junk_in_quality_measure.xml

- Fix for the `value:true` encoding bug in the measure section reference and results node.
- Forces a whitelist in the measure section v2 encoder as it does not need any other template id's encoded. If other template id's need to be encoded here in the future, they can be added.

Measure Reference and Results Bug

---

commandline/src/test/resources/measures-data.json
commons/src/main/resources/measures-data.json
converter/src/main/java/gov/cms/qpp/conversion/encode/MeasureDataEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/util/SubPopulationHelper.java
converter/src/main/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidator.java
converter/src/test/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoderTest.java
converter/src/test/java/gov/cms/qpp/conversion/util/SubPopulationHelperTest.java
sample-files/2018/mipsCms347v1SampleFile.xml

- QPPCT-1043
- Creates a new way for encoding CMS347v1. 
- The new encoding takes the sum of all subpopulations for each metric type. The reason it was added into the encoding process is because decoding cannot be changed. CMS347v1 requires submission with 3 Subpopulation strata and then to be converted into one with the sum of each subpopulations of same metric type be summed.
- Adds guids into `measures-data.json` for CMS347v1
-

Fix CMS347v1

---

generate/pom.xml
generate/src/main/java/gov/cms/qpp/generator/ErrorCodeDocumentationGenerator.java
generate/src/test/java/gov/cms/qpp/generator/ErrorCodeDocumentationGeneratorTest.java
pom.xml

- The generate maven plugin writes in the working dir even if that dir is the converter project.
- ErrorCodeDocumentationGenerator now checks the working dir compared to the parent project path and creates an appropriate path modifier to compensate for running in either the parent project or the converter project.
- [-] Added and updated JavaDocs for non-test classes and methods.

Fix ERROR_MESSAGES.md written in converter project dir.

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
converter/src/main/java/gov/cms/qpp/conversion/encode/ClinicalDocumentEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
converter/src/test/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidatorTest.java
sample-files/2019/cpcPlusMissingNpi.xml
sample-files/2019/cpcPlusMissingTin.xml

- QPPSF-4909
- NPI and TIN are now required in the QRDA-III format for CPC+ submissions.
- NPI and TIN are still not encoded into QPP.
- Unit tests added for missing tin and npi.
- sample files added for manual testing.

CPC+ TIN & NPI validation Changes

---

converter/src/test/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoderTest.java

- This was missed from the previous PR: https://github.com/CMSgov/qpp-conversion-tool/pull/898

add decoder test for NPI & TIN

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
converter/src/main/java/gov/cms/qpp/conversion/validate/Checker.java
converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
converter/src/test/java/gov/cms/qpp/conversion/validate/CheckerTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidatorTest.java
sample-files/2019/cpcWithIaExample.xml
sample-files/2019/cpcWithPiExample.xml

- QPPSF-5064
- Validation for CPC+ submissions to add a warning when a cpc+ submission includes IA or PI sections.

CPC+ Warning for IA/PI Sections

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
converter/src/main/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureSectionValidator.java

- QPPSF-5066
- Slight change to remove error code 65 as it is no longer required.

Remove overall checker

---

rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Constants.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/DbServiceImpl.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/acceptance/CpcApiAcceptance.java

- Changes the CPC+ filter date for unprocessed CPC+ conversion from static to an environment variable. This will allow us to deploy a proper date filter without having to deploy new code.

CPC Plus Filter Start Date

---

converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
converter/src/main/resources/pathing/path-correlation.json
converter/src/test/java/gov/cms/qpp/SingularAttributeTest.java
converter/src/test/java/gov/cms/qpp/acceptance/CpcPlusRoundTripTest.java
converter/src/test/java/gov/cms/qpp/conversion/encode/PiSectionEncoderMultiMeasureTest.java

- Fixes #_. 
While generating json from QRDAIII cehrt should be cehrtId
modified:   converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
modified:   converter/src/main/resources/pathing/path-correlation.json
modified:   converter/src/test/java/gov/cms/qpp/SingularAttributeTest.java
modified:   converter/src/test/java/gov/cms/qpp/acceptance/CpcPlusRoundTripTest.java
modified:   converter/src/test/java/gov/cms/qpp/conversion/encode/PiSectionEncoderMultiMeasureTest.java

cehrt name should be cehrtId accourding to qpp score view end point

---

rest-api/src/main/java/gov/cms/qpp/conversion/api/services/AnyOrderActionService.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/DbServiceImpl.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/StorageServiceImpl.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/AnyOrderAsyncActionServiceTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/InOrderAsyncActionServiceTest.java

- JIRA story QPPSF-5525.
- Limited retries to 5 times
- More sane backoff periods
- Added a name to each async action service to enhance monitoring

End retries after 5 attempts, enhanced retry logging

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
converter/src/test/java/gov/cms/qpp/acceptance/cpc/CpcPlusAcceptanceTest.java
converter/src/test/resources/cpc_plus/success/ComprehensivePrimaryCareSampleQRDA-III_SDE.xml
sample-files/2019/cpcPlusMultiValidApmCombo.xml

- QPPSF-5650
- Removes the warning for missing cehrt id's in CPC+ submissions
- Adds tests and sample file to ensure warnings do not appear for submissions without cehrt id's

CPC+ Cehrt ID Warning Removal

---

rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/DbServiceImpl.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/internal/DbServiceImplTest.java

- QPPSF_5592
- Changes sorting to use queryPage again but instead filter with the GSI's sort key date. This solves the issue of limitations being ignored and applies filtering for year 2020. The only issue is the filtering will start for every date in 2020 rather than January 02, 2020. This should not be a problem as the conversion tool isn't accessible until January 02, 2020 regardless.

Update CPC Unprocessed list filtering

---

ERROR_MESSAGES.md
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/DbServiceImpl.java

- Optimizes Query search by filtering more with the Sort key.
- In the future, I would want find a way to actually limit the query as DynamoDbMapper.DynamoDBQueryExpression.withLimit doesn't actually limit in a Query. The optimization works in Dev and Imp. Before proceeding on adding features that completely change how we gather data from Dynamo, I would like to ensure this optimization reaches Prod and close the current bug ticket.

QPPSF-5592: Optimize sort filter of dynamo Query.

---

.github/workflows/ecr-publish.yml

- JIRA story QPPSF-6618.
Integrate the [slack-notify-build](https://github.com/marketplace/actions/slack-notify-build) GitHub Action to print the build or deploy status to Slack (p-qpp-sub-alerts).

QPPSF-6618: Added slack notifications for GitHub Actions

---

.github/workflows/ecr-publish.yml

- JIRA story QPPSF-6618.
Integrate the [slack-notify-build](https://github.com/marketplace/actions/slack-notify-build) GitHub Action to print the build or deploy status to Slack (p-qpp-sub-alerts).
- Modified the if condition to include the branch.
`if: github.ref == 'refs/heads/develop' && success()`
- Updated the GitHub SLACK_BOT_TOKEN with a new token after Freddie added additional permissions.

QPPSF-6618: Modified the Slack notifications with modified condition

---

converter/src/main/java/gov/cms/qpp/conversion/encode/ClinicalDocumentEncoder.java
converter/src/test/java/gov/cms/qpp/acceptance/QualityMeasureIdRoundTripTest.java
sample-files/2020/MIPS_APM_Entity_Submission.xml

- Fixes issue with practice site id being converted on a mipsapm program submission.

Remove Practice Site ID from measure level

---

rest-api/src/main/java/gov/cms/qpp/conversion/api/config/SecurityConfig.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/CpcFileControllerV1.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/helper/MetadataHelper.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Constants.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Metadata.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/security/JwtAuthorizationFilter.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/CpcFileService.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/DbService.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/CpcFileServiceImpl.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/DbServiceImpl.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/CpcFileControllerV1Test.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/ExceptionHandlerControllerV1Test.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/model/ConstantsTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/model/MetadataTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/security/JwtAuthorizationFilterTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/internal/CpcFileServiceImplTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/internal/DbServiceImplTest.java

- https://jira.cms.gov/browse/QPPSF-6654
- Adds new metadata field `RtiProcessed_CreateDate` to allow data storage and filtering for the RTI team.
- New security configuration stored as an ENV called `RTI_ORG_NAME` to allow any organization with proper JWT organization access. Using an environment variable to allow security around the name and being able to change and deploy easily (The tokens have not been requested yet however,  we can test with any token for now until proper tokens are made)
- Updated CPC+ APIs
- Retrieve Unprocessed files now takes an organization i.e. `rti` or `cpcplus` to decide which team is pulling the list.
- Retreive QRDA-III and QPP-json is the same.
- Processing/Unprocessing api now takes an org name as well to filter which team has processed a file.
- Unit …

QPPSF-6654: RTI API Processing updates.

---

converter/src/main/java/gov/cms/qpp/conversion/Context.java
converter/src/main/java/gov/cms/qpp/conversion/model/validation/ApmEntityIds.java
converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
converter/src/test/java/gov/cms/qpp/acceptance/ClinicalDocumentExtensionTest.java
converter/src/test/java/gov/cms/qpp/acceptance/CpcPlusRoundTripTest.java
converter/src/test/java/gov/cms/qpp/acceptance/QualityMeasureIdRoundTripTest.java
converter/src/test/java/gov/cms/qpp/acceptance/cpc/CpcPlusAcceptanceTest.java
converter/src/test/java/gov/cms/qpp/conversion/model/validation/ApmEntityIdsTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidatorTest.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Constants.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/StorageService.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/QrdaServiceImpl.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/StorageServiceImpl.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/QrdaRestIntegrationTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/internal/QrdaServiceImplTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/internal/StorageServiceImplTest.java
rest-api/src/test/resources/test_apm_entity_ids.json

- Allows the rest api to have a configurable APM validation file. Testing environments can now allow any value we choose to be a proper APM. The validation from the Submission API can specify any test APMs they use and we can configure this to work for CT.

QPPSF-6546: APM validation file

---

.github/workflows/ci-build.yml
ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ProblemCode.java
converter/src/main/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidator.java
converter/src/test/java/gov/cms/qpp/acceptance/QualityMeasureIdMultiRoundTripTest.java
converter/src/test/java/gov/cms/qpp/acceptance/QualityMeasureIdRoundTripTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureIdValidatorTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidatorTest.java
converter/src/test/resources/cpc_plus/failure/fixture.json
rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/QrdaServiceImpl.java

- Updates the Initial Population to Denominator validations
- Denom. allowed to be <= I. Pop for non CPC+ submissions
- Denom = Ipop for CPC+ submissions.
-

QPPSF-7444: Ipop Denom Validations

---

converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
converter/src/main/java/gov/cms/qpp/conversion/model/Program.java
converter/src/main/java/gov/cms/qpp/conversion/util/MeasureConfigHelper.java
converter/src/main/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidator.java
converter/src/test/resources/cpc_plus/failure/fixture.json
sample-files/2020/MIPS_APM_Entity_Submission.xml
valid-QRDA-III-latest-qpp.json

- Initial measure specific validations
- Update Ipop & Denom validation to include only the 2 CPC+ measures (CMS122v8, CMS165v8) for validation.
Addition:
- Update mips apm submissions to be excluded from cpc+ validations and included as mips.

QPPSF-7456: Measure Specific Validations

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ProblemCode.java
converter/src/main/java/gov/cms/qpp/conversion/validate/CpcMeasureDataValidator.java
converter/src/test/java/gov/cms/qpp/conversion/validate/CpcMeasureDataValidatorTest.java

- Removes the extra supplemental data validation

QPPSF-7463: Revert Supplemental Validation

---

infrastructure/terraform/dev/iam-ecs-gh/iam-gh-ecs.tf

- Fixes #_.
QPPSF-8434
- *Added iam policy, user "github-actions-ecr" gives permissions to describe task definitions* as needed for current conversion-tool git-hub workflow

QPPSF-8434 - Added iam user policy permissions to describe taskdefinition

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ProblemCode.java
commons/src/main/resources/measures-data.json
converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
converter/src/main/java/gov/cms/qpp/conversion/validate/PcfClinicalDocumentValidator.java
converter/src/test/java/gov/cms/qpp/acceptance/NegativePcfRoundTripTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidatorTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/PcfClinicalDocumentValidatorTest.java
converter/src/test/resources/cpc_plus/failure/fixture.json

- Updates error messages that include `CPC & PCF` verbiage to now accept program name as input to be more precise in error message formatting.
- Fixes the issue with the APM combination warning message outputting only CPC+ program name. It will now output PCF program name on PCF submissions

QPPSF-8394: Update Error messaging

---

converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
converter/src/main/java/gov/cms/qpp/conversion/encode/ClinicalDocumentEncoder.java
converter/src/main/java/gov/cms/qpp/conversion/model/Program.java
converter/src/main/resources/pathing/path-correlation.json
converter/src/test/java/gov/cms/qpp/SingularAttributeTest.java
converter/src/test/java/gov/cms/qpp/acceptance/QualityMeasureIdRoundTripTest.java
converter/src/test/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoderTest.java
converter/src/test/java/gov/cms/qpp/conversion/encode/ClinicalDocumentEncoderTest.java
converter/src/test/resources/Mips-Apm-Entity-2021.xml
sample-files/2021/App1-ApmEntity-Qrda-III.xml
sample-files/2021/App1-Group-QRDA-III.xml
sample-files/2021/App1-Indv-QRDA-III.xml

- QPPSF-8778
- Updates Mips Apm submissions to use the XML program name `MIPS_APMENTITY` instead of `MIPS_APM`
- Updates the location in XML where the Apm Entity id is found for `MIPS_APP1_APMENTITY` and `MIPS_APMENTITY`
- Updates test coverage for `MIPS_APP1_APMENTITY` and `MIPS_APMENTITY`
- Adds a new, happy-path sample files for APP Individual, Group and ApmEntity.

QPPSF-8778: APP1 Apm Entity Fixes

---

.dockerignore
Dockerfile
mvn-entrypoint.sh
settings-docker.xml

- Updates the base image of docker to Redhat's adoptopenjdk 11
- This is due to debian's openjdk 11 having issues with bullseye and critical failures coming from debians sid build.

QPPSF-9108: Fix Base Image Vulnerabilities

---

infrastructure/ecr-notification-lambda/.terraform.lock.hcl
infrastructure/ecr-notification-lambda/ecr-lambda-notification.py
infrastructure/ecr-notification-lambda/ecr-scan-notification.tf
infrastructure/ecr-notification-lambda/terraform.tfvars
infrastructure/ecr-notification-lambda/variables.tf

- Fixes #_.
QPPSF-8243
- Creates lambda function for sending ECR Scan findings to scoring slack channel
- Creates Event-bridge rule to trigger event after image scan is complete and with latest tag
- Creates SSM parameter to store slack web-hook url
- Creates lambda execution role & policy

QPPSF-8243, ECR scan notification lambda for Conversion-Tool

---

.github/workflows/checkov-tf.yml
infrastructure/terraform/dev/.terraform.lock.hcl
infrastructure/terraform/dev/main.tf
infrastructure/terraform/devpre/.terraform.lock.hcl
infrastructure/terraform/devpre/main.tf
infrastructure/terraform/impl/.terraform.lock.hcl
infrastructure/terraform/impl/main.tf
infrastructure/terraform/modules/ssm.tf
infrastructure/terraform/prod/.terraform.lock.hcl
infrastructure/terraform/prod/main.tf

- Fixes #_.
QPPSF-8326
QPPSF-9309
**QPPSF-8326**
- _Upgraded terraform required_version from `0.15.5` to `1.0.0`_
- _Upgraded aws provider version from `3.67.0` to `3.70.0`_
- _Ran terraform init and plan in all Environments_
**QPPSF-9309**
- Remediated Checkov failed policies:
SSM Parameter should be Encrypted, Modified ssm parameter type from `String` to `SecureString`
Skipped checks on `CKV_AWS_173`,`CKV_AWS_32` policies

QPPSF-9309, QPPSF-8326 - TF upgrade to v1, remediated Checkov failed policies

---

infrastructure/terraform/modules/Kinesis-cloudwatch-splunk/README.md
infrastructure/terraform/modules/Kinesis-cloudwatch-splunk/index.js
infrastructure/terraform/modules/Kinesis-cloudwatch-splunk/lib/splunklogger.js
infrastructure/terraform/modules/ecs.tf
infrastructure/terraform/modules/iam.tf
infrastructure/terraform/modules/kinesis-lambda.tf
infrastructure/terraform/modules/kinesis.tf

- Fixes #_.
_QPPSF-9296_
- Added Lambda function code to forward Cloudwatch log groups to Splunk
**Terraform code:**
- Creates CT Cloudwatch log groups subscription filter to kinesis stream
- Creates IAM Role permissions to allow Cloudwatch logs to write to Kinesis Stream
- Creates lambda function resource and event source mapping 
- Creates Kinesis Stream per Environment

QPPSF-9296, Forward Conversion-Tool Cloudwatch logs to Splunk

---

infrastructure/terraform/modules/alb.tf

- Fixes #_.
_QPPSF-10053_
_Currently, qppsf-conversion-tool-lb-{env} is not set to drop invalid headers. Allowing invalid headers can introduce unforeseen security issues, so it's best to ensure this setting is enabled on all ALBs_
Added attribute `drop_invalid_header_fields = true` to all CT ALBs

QPPSF-10053, Added drop http header attribute for CT ALB

---

infrastructure/terraform/dev/github-user.tf

- Fixes #_.
_QPPSF-10054_
Github actions ECR has an inline policy permissions attached which is not recommended as per Trusted Advisor Alert, IAM users should not have IAM policies attached directly, IAM users have policies attached. Instead, IAM users must inherit permissions from IAM groups or roles.
- Imported iam group `github-actions-push` in terraform state
- Removed iam user inline policy and added permissions to the group

QPPSF-10054, Added GHA ecr user permissions to iam group

---

.github/workflows/ci-build.yml

- JIRA story https://jira.cms.gov/browse/QPPSF-10419.
- Adds a CI step to delete `~/.m2` Maven repository before building. This was causing a Snyk vulnerability error due to old dependencies being present.

Add CI build step to delete ~/.m2

---

converter/src/main/java/gov/cms/qpp/conversion/encode/JsonWrapper.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v2/QrdaControllerV2.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v2/ZipController.java
rest-api/src/main/java/gov/cms/qpp/conversion/api/model/ConvertResponse.java
rest-api/src/main/resources/application.properties
rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v2/QrdaControllerV2Test.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v2/ZipControllerTest.java

- Fixes a Jackson issue with Spring not accepting the `JsonWrapper.toObject` due to redundancy issues.

QPPSF-10417: Jackson/Spring issue

---

commons/src/main/java/gov/cms/qpp/conversion/model/validation/SubPopulation.java
commons/src/main/java/gov/cms/qpp/conversion/model/validation/SubPopulationLabel.java
converter/src/main/java/gov/cms/qpp/conversion/decode/MeasureDataDecoder.java
converter/src/main/java/gov/cms/qpp/conversion/encode/MeasureDataEncoder.java
converter/src/test/java/gov/cms/qpp/acceptance/MeasureDataRoundTripTest.java
converter/src/test/java/gov/cms/qpp/conversion/model/validation/SubPopulationsTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidatorTest.java
converter/src/test/resources/fixtures/measureDataHappy.xml
converter/src/test/resources/reduced-test-measures-data.json

- Adds decoding and validation for the new numerator exclusion field.
- Ability to read the numerator exclusion field in the measures data configuration.
- Adds test coverage of the new field.

QPPSF-10934: Numerator exclusion

---

.github/workflows/ecr-publish.yml

- Fixes #_.
QPPSF-11270
- *Removed deprecated commands from Github Actions, `set-output`*
**Reference**: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

QPPSF-11270 - Removed depreciated commands in workflow

---

test-coverage/pom.xml

- Adds a filter to the test-coverage pom to ignore spring-bean v5.2.2.RELEASE
- This dependency was not being used but was added by maven transient dependencies.

QPPSF-10587: Remove unnecessary dependency

---

infrastructure/terraform/modules/ecs.tf
infrastructure/terraform/modules/s3.tf

- Fixes #_.
QPPSF-11183
As part of [QPPPM-2442] archiving strategy discussions we identified that the log files can be archived after 365 days. 
AU-11 Audit Record Retention (High, Moderate, Low)
The organization retains audit records for ninety (90) days and archive old records for one (1) year to provide support for after-the-fact investigations of security incidents and to meet regulatory and CMS information retention requirements
- *Change Cloudwatch Log Retention period to 365 days and Cloudwatch *
- *Update s3 lifecycle to remove objects after year*

QPPSF-11183- log retention period set for CloudWatch and S3

---

commons/src/main/resources/measures-data.json
converter/src/main/java/gov/cms/qpp/conversion/encode/PiSectionEncoder.java
converter/src/test/java/gov/cms/qpp/acceptance/PiSectionRoundTripTest.java
converter/src/test/resources/app/2022/App1-ApmEntity-Qrda-III.xml
converter/src/test/resources/app/2022/App1-Group-QRDA-III.xml
converter/src/test/resources/app/2022/App1-Indv-QRDA-III.xml
rest-api/pom.xml
sample-files/2022/App1-ApmEntity-Qrda-III.xml
sample-files/2022/App1-Group-QRDA-III.xml
sample-files/2022/App1-Indv-QRDA-III.xml

- App1 now allows the CEHRT Identifier to be converted in it's PI Measurement Set Section when it is provided in the QRDA-III XML.

QPPSF-11741: APP1 CEHRT Identifier fix

---

infrastructure/terraform/modules/s3.tf

- Fixes #_.
Terraform will perform the following actions:
~ resource "aws_iam_policy" "conversiontool_ecs_task_exec_policy" {
id        = "arn:aws:iam::003384571330:policy/delegatedadmin/developer/qppsf-dev-conversiontool-ecsTaskExecutionRole-role-policy"
name      = "qppsf-dev-conversiontool-ecsTaskExecutionRole-role-policy"
~ policy    = jsonencode(
~ {
~ Statement = [
{
Action   = [
"s3:GetAccessPoint",
"ssm:DescribeDocument",
"kms:GenerateRandom",
"ec2messages:GetEndpoint",
"ssmmessages:OpenControlChannel",
"ec2messages:GetMessages",
"ssm:PutConfigurePackageResult",
"ssm:ListInstanceAssociations",
"ssm:GetParameter",
"ssm:UpdateAssociationStatus",
"ssm:GetManifest",
"kms:DescribeCustomKeyStores",
"kms:DeleteCustomKeyStore",
"ec2messages:DeleteMessage", …

upgrades for new S3 resource attachments

---

.github/CODEOWNERS
buildspec.yml

- When new participation file is uploaded to S3, the automation script need to get the file from the S3 and process it automatically.  This was not working.  In order to fix that, when we added a SSM variable before, we were getting 403 forbidden error.  So took care of this process manually before.  Now the CT tool is in PROD, checking back on this issue.  We will only be able to see the error in codebuild, when this change is merged to develop.  Once this is merged, I will work with Raj/Tim on this.

QPPSE-1584: Added Parameter Store variable to the buildspec to fix the automation script

---

converter/pom.xml
converter/src/main/java/gov/cms/qpp/conversion/encode/JsonWrapper.java
converter/src/main/java/gov/cms/qpp/conversion/model/Node.java
converter/src/main/java/gov/cms/qpp/conversion/util/CloneHelper.java
converter/src/test/java/gov/cms/qpp/conversion/encode/JsonWrapperTest.java
pom.xml

- Removes unsupported clone library and new in memory serialization is implemented to deep clone.  This should fix the converter issue and test case failures.  This way, we do not have to add optional parameters to bypass java 17 enhancements.  Rest API and other test cases will be fixed later.
Note: Tried kryo for deep cloning, but had issues with it.  So, wrote custom cloning.  Also, some of the reflective access is not supported in Java 17.  Mockito was trying to do that, so had to remove few test cases.
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for QPP Conversion Tool 2023.6.0-RELEASE:
[INFO] 
[INFO] QPP Conversion Tool ................................ SUCCESS [  0.002 s]
[INFO] Test Commons …
```

[QPPSE-1927]: Removed unsupported clone library and written in memory serialization for cloning to fix test case failures and cloning issues

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ProblemCode.java
commons/src/main/resources/measures-data.json

- The UUID information has been moved from Table 14 to Table 15 in 2023 Implementation guide.  All the references to Table 14 needs to be updated to Table 15.
- https://jira.cms.gov/browse/QPPSE-2001

QPPSE-2001: Updated references of UUID table info to reflect 2023 IG

---

commandline/src/test/java/gov/cms/qpp/conversion/ConversionFileWriterWrapperTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/config/DynamoDbConfigTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/config/KmsConfigTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/config/S3ConfigTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/security/JwtAuthorizationFilterTest.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/services/internal/AuditServiceImplTest.java

- With Java 17, the reflective access is restricted.  So, current version of Mockito with JUnit4 was not able to mock static classes or methods.  For now, commenting those tests.  However, based on further research, in order to resolve it, we can add explicit access by passing --add-opens parameter to scope test.  However, when I tested Mockito with JUnit5 it seems to work without those parameters.  So, will be checking further on this to bring the tests back without having to pass in those parameters.  Worst case, will add the tests back with the parameters passed.  Just wanted avoid these for security reasons if possible.
https://docs.oracle.com/en/java/javase/17/migrate/migrating-jdk-8-later-jdk-releases.html#GUID-12F945EB-71D6-46AF-8C3D-D354FD0B1781
```
<argLine>
--add-opens …
```

QPPSE-1928: Fixed Test Cases for rest of the modules

---

infrastructure/terraform/modules/ecs.tf
infrastructure/terraform/modules/iam.tf
infrastructure/terraform/modules/ssm.tf

- Fixes 
- Permissions policy alignment in TF Source with deployed DEV resources to allow Codebuild project to run from Github Webhook Event
- SG rule adjustments in TF Source with deployed DEV resources
- the attached plan IS NOT YET APPLIED in DEV (previous work on ECR lifecycle policy implementation, shared account tagging implications).
[ct-dev-202404050815.plan.txt](https://github.com/CMSgov/qpp-conversion-tool/files/14884972/ct-dev-202404050815.plan.txt)

QPPSE-2171 DEV Codebuild Cleanup and alignment with resources

---

rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Constants.java

- Updates cpcplus endpoint to telligen
- Existing Dev QPP Auth token was not working.  Reset the tokens, deployed user branch and tested the endpoint successfully.  Below url currently should work, until there are not any changes to develop branch.
- https://dev.qpp.cms.gov/api/submissions/converter/pcf/unprocessed-files/telligen
- https://jira.cms.gov/browse/QPPSE-1483

QPPSE-1483: Updated cpcplus org name to telligen

---

converter/pom.xml
converter/src/test/java/gov/cms/qpp/CacheBuilder.java
converter/src/test/java/gov/cms/qpp/acceptance/ClinicalDocumentExtensionTest.java
converter/src/test/java/gov/cms/qpp/acceptance/NegativePcfRoundTripTest.java
converter/src/test/java/gov/cms/qpp/acceptance/Pcf2024AcceptanceTest.java
converter/src/test/java/gov/cms/qpp/acceptance/PcfRoundTripTest.java
converter/src/test/java/gov/cms/qpp/acceptance/QualityMeasureIdRoundTripTest.java
converter/src/test/java/gov/cms/qpp/conversion/model/validation/ApmEntityIdsTest.java
converter/src/test/java/gov/cms/qpp/conversion/validate/PcfClinicalDocumentValidatorTest.java
converter/src/test/java/gov/cms/qpp/model/CacheType.java
pom.xml

- Added test file caching for apm/pcf entity ids json file.  For the rest of the files, detailed analysis would be needed and a separate ticket will be created.
- https://jira.cms.gov/browse/QPPSE-314

QPPSE-314: Added caching for apm entity json files

---

rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/ValidationServiceImpl.java

- When returned submission data cannot be converted to CT, the 500 Internal Server error has been fixed.

QPPSE-2865: Fix submission error conversion issue

---

.env
infrastructure/terraform/modules/templates/conversion_tool_task_def.tpl
infrastructure/terraform/secure/secret-template.tf

- Fixes: Added IMPL_ACA_Cookie.
- JIRA story: QPPSE-2864.
-
-

QPPSE-2864: Added IMPL_ACA_Cookie.

---

rest-api/src/main/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidator.java
rest-api/src/test/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidatorTest.java

- When root id for TIN value is null, CT returns unexpected error.  Fixed to return valid error message.

QPPSE-2783: Added fix for the null TIN root id issue

---

ERROR_MESSAGES.md
commons/src/main/java/gov/cms/qpp/conversion/model/error/ProblemCode.java
commons/src/main/resources/measures-data.json
rest-api/src/main/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidator.java

- Fixed typo in problem codes
- https://jira.cms.gov/browse/QPPSE-2999

QPPSE-2999: Fix typo in problem codes

---

Dockerfile

- JIRA story https://jira.cms.gov/browse/QPPA-10640
- improve maven binary download curl command with increased timeout limit and retry logic

QPPA-10640: Improve maven binary download command
