- circle.yml
- tools/ansible/conversion_playbook.yml
- Improvement not related to a JIRA story or GitHub issue.
- Properly reference the image tar file
- Add `NO_AUDIT` to the environment so no auditing occurs.
> Fix Flexion's Small Environment

- demos/QPPCT-348.md
- frontend/src/polyfills.ts
- JIRA story QPPCT-348
- added es6 pollyfills
> QPPCT-348: ie polyfills

- demos/QPPCT-339.md
- JIRA story QPPCT-339.
- Demo file
> QPPCT-339: Demo file

- demos/QPPCT-320.md
- demos/QPPCT-425.md
- demo files
- added demo files
> demo files

- .circleci/config.yml
- frontend/package.json
- tools/bin/docker_deploy.sh
- tools/bin/signal_success.sh
- JIRA story QPPCT-407
- adds workflow for simple ui test and deployment
> QPPCT-407: simple UI workflow

- demos/QPPCT-431.md
- JIRA story QPPCT-431.
- Demo file for QPPCT-431.
> QPPCT-431: Demo file

- demos/QPPCT-440.md
- JIRA story QPPCT-440.
- Added the demo file for QPPCT-440.
> QPPCT-440: demo file

- converter/src/main/java/gov/cms/qpp/conversion/Converter.java
- converter/src/main/java/gov/cms/qpp/conversion/correlation/PathCorrelator.java
- converter/src/test/java/gov/cms/qpp/conversion/ConversionReportTest.java
- converter/src/test/java/gov/cms/qpp/conversion/correlation/PathCorrelatorTest.java
- converter/src/test/java/gov/cms/qpp/conversion/encode/JsonWrapperTest.java
- converter/src/test/java/gov/cms/qpp/conversion/model/RegistryTest.java
- converter/src/test/java/gov/cms/qpp/conversion/model/error/AllErrorsTest.java
- converter/src/test/java/gov/cms/qpp/conversion/model/error/DetailTest.java
- converter/src/test/java/gov/cms/qpp/conversion/model/error/ErrorTest.java
- converter/src/test/java/gov/cms/qpp/conversion/model/validation/MeasureConfigTest.java
- converter/src/test/java/gov/cms/qpp/conversion/model/validation/SubPopulationTest.java
- pom.xml
- tools/bin/sonarqube.sh
- QPPCT-441
- Increased test coverage
> QPPCT-441: test coverage

- demos/QPPCT-422.md
- JIRA story QPPCT-422.
- Demo file
> QPPCT-422: Demo

- demos/QPPCT-378.md
> QPPCT-378 : Demo file

- ERROR_MESSAGES.md
- QPPCT-458
- Update ERROR_MESSAGES.md with error codes.
- Remove Message Duplication.
> Update Error Messages Markdown

- .circleci/config.yml
- QPPCT-454
- Change the ui deployment branch from `master` to `ui_deployment`
> Change UI Deployment branch

- benchmark/src/test/java/gov/cms/qpp/conversion/ConverterLoadTest.java
- benchmark/src/test/java/gov/cms/qpp/conversion/ParameterizedBenchmarkTest.java
- test-commons/src/main/java/gov/cms/qpp/test/LoadTestSuite.java
- Fixes builds running the benchmark all the time
> Upgrade benchmarks to junit 5

- frontend/src/app/app.component.html
- frontend/src/app/app.component.ts
- JIRA story QPPCT-457
- Allows for repeated processing of uploaded qrda files
> QPPCT-457: re-downloadable

- frontend/src/app/app.component.ts
> Update Simple UI to use Nava's Prod URL

- converter/src/test/java/gov/cms/qpp/SingularAttributeTest.java
- converter/src/test/java/gov/cms/qpp/acceptance/AutoDetectQrdaTest.java
- converter/src/test/java/gov/cms/qpp/acceptance/ClinicalDocumentRoundTripTest.java
- converter/src/test/java/gov/cms/qpp/acceptance/CpcTest.java
- converter/src/test/java/gov/cms/qpp/acceptance/IaSectionRoundTripTest.java
- converter/src/test/java/gov/cms/qpp/acceptance/MeasureDataRoundTripTest.java
- converter/src/test/java/gov/cms/qpp/acceptance/MeasureDataTest.java
- converter/src/test/java/gov/cms/qpp/acceptance/MultipleTinRoundTripTest.java
- converter/src/test/java/gov/cms/qpp/acceptance/XpathJsonPathComparisonTest.java
- converter/src/test/java/gov/cms/qpp/conversion/ContextTest.java
- converter/src/test/java/gov/cms/qpp/conversion/InputStreamQrdaSourceTest.java
- converter/src/test/java/gov/cms/qpp/conversion/PathQrdaSourceTest.java
- converter/src/test/java/gov/cms/qpp/conversion/QrdaSourceTestSuite.java
- converter/src/test/java/gov/cms/qpp/conversion/ScopedConversionTest.java
- converter/src/test/java/gov/cms/qpp/conversion/correlation/PathCorrelatorTest.java
- converter/src/test/java/gov/cms/qpp/conversion/correlation/QrdaQppAssociationTest.java
- converter/src/test/java/gov/cms/qpp/conversion/model/validation/ComponentKeyTest.java
- converter/src/test/java/gov/cms/qpp/conversion/model/validation/MeasureConfigTest.java
- converter/src/test/java/gov/cms/qpp/conversion/model/validation/MeasureConfigsTest.java
- converter/src/test/java/gov/cms/qpp/conversion/model/validation/SubPopulationTest.java
- converter/src/test/java/gov/cms/qpp/conversion/model/validation/SubPopulationsTest.java
- converter/src/test/java/gov/cms/qpp/conversion/segmentation/QrdaScopeTest.java
- converter/src/test/java/gov/cms/qpp/conversion/util/EnvironmentHelperTest.java
- converter/src/test/java/gov/cms/qpp/conversion/util/JsonHelperTest.java
- converter/src/test/java/gov/cms/qpp/conversion/xml/XmlExceptionTest.java
- converter/src/test/java/gov/cms/qpp/conversion/xml/XmlUtilsTest.java
> Junit5 timebox

- sample-files/MIPS_GROUP_QRDA_III_ACI_IA_Sample1.xml
- sample-files/MIPS_GROUP_QRDA_III_ACI_IA_Sample2.xml
- sample-files/MIPS_GROUP_Sample_QRDA_III.xml
- sample-files/README.md
- Changes requested via https://jira.cms.gov/browse/QPPQS-589
- Added ACI attestation measures to the 3 files containing ACI measures
- Updated README
-
> Adding ACI attestation measures

- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/ExceptionHandlerControllerV1.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/QrdaControllerV1.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/AuditServiceImpl.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/DbServiceImpl.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/StorageServiceImpl.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/ValidationServiceImpl.java
Improvement task.
- Modified existing logging statements to be more clear.
- Added new logging statements to make future triaging easier.
> Modified and added more logging to the ReST API

- frontend/src/index.html
See discussion on https://jira.cms.gov/browse/QPPFED-460
- JIRA story QPPFED-460
- Removes the base element
> Remove base element

- converter/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- converter/src/main/java/gov/cms/qpp/conversion/util/EnvironmentHelper.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidatorTest.java
- JIRA story QPPCT-484.
- Error if conversion after the end of the submission window
> CPC+ Validation - Error if conversion after the end of the submission window

- converter/src/main/java/gov/cms/qpp/conversion/decode/QppXmlDecoder.java
- converter/src/main/java/gov/cms/qpp/conversion/decode/XmlInputDecoder.java
- JIRA story QPPCT-413.
- Stopped using reflection for namespace code
> Decode optimizations

- benchmark/pom.xml
- commandline/pom.xml
- converter/pom.xml
- frontend/package.json
- generate-qrda/pom.xml
- pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
Bumping all POM versions to 0.22 for the next release tag.
> bump all POM versions to 0.22

- pom.xml
> better integration exclusion

- .circleci/config.yml
- JIRA story Cannot create Jira story, access still broken.
- Disables logging download progress in the maven build. This will hopefully allow us to not need to download the build output when it fails.
> Run maven with batch mode on circleci

- benchmark/pom.xml
- commandline/pom.xml
- converter/pom.xml
- frontend/package.json
- generate-qrda/pom.xml
- pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
> version bump to 0.30

- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/HealthCheckController.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/HealthCheck.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/HealthCheckControllerTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/model/HealthCheckTest.java
> Expand health check endpoint

- benchmark/pom.xml
- commandline/pom.xml
- converter/pom.xml
- frontend/package.json
- generate-qrda/pom.xml
- pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
bumps the version of conversion tools to 0.31 beta
> bump version to 0.31

- benchmark/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate-qrda/pom.xml
- pom.xml
- rest-api/pom.xml
- rest-logging/pom.xml
- test-commons/pom.xml
> bump version to 0.32-beta

- benchmark/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate-qrda/pom.xml
- pom.xml
- rest-api/pom.xml
- rest-api/src/main/java/gov/cms/qpp/conversion/api/helper/MetadataHelper.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/helper/MetadataHelperTest.java
- rest-logging/pom.xml
- test-commons/pom.xml
- Fixes QPPCT-554
- Addresses 500 errors generated due to malformed xml
> QPPCT-554: better handling for malformed xml

- benchmark/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate-qrda/pom.xml
- pom.xml
- rest-api/pom.xml
- rest-logging/pom.xml
- test-commons/pom.xml
> Deploy v1.0 to DEV

- benchmark/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate-qrda/pom.xml
- pom.xml
- rest-api/pom.xml
- rest-logging/pom.xml
- test-commons/pom.xml
> bump version to 1.1

- rest-api/pom.xml
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/ValidationServiceImpl.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/ValidationServiceImplTest.java
- test-commons/src/main/java/gov/cms/qpp/test/AroundEach.java
- test-commons/src/main/java/gov/cms/qpp/test/logging/LoggerContract.java
- JIRA story QPPCT-204.
- Log environment variable, or if it us unset
> Check for VALIDATION_URL env var at endpoint startup

- tools/ansible/conversion_playbook.yml
- JIRA story QPPCT-566.
- Adds environment variables to our Docker instance so that it can interact with S3, DynamoDB, etc.
> QPPCT-566: Added extra environment variables to docker container

- pom.xml
- Fixes issues when launching from inside Eclipse.
- JIRA story QPPCT-586.
- Adds JUnit 5 Launcher dependency
> Adds JUnit 5 Launcher dependency

- benchmark/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate-qrda/pom.xml
- pom.xml
- rest-api/pom.xml
- rest-logging/pom.xml
- test-commons/pom.xml
- tools/docker/docker-artifacts/newrelic/newrelic.yml
- QPPCT-592
- resolves NewRelic agent startup error when parsing config
> QPPCT-592: non-yaml comment

- benchmark/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate-qrda/pom.xml
- pom.xml
- rest-api/pom.xml
- rest-logging/pom.xml
- test-commons/pom.xml
> Bump version to 1.1.3

- benchmark/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate-qrda/pom.xml
- pom.xml
- rest-api/pom.xml
- rest-logging/pom.xml
- test-commons/pom.xml
> bumping the version to 1.1.4

- frontend/package.json
- Fixes yarn to run lint again.
- M.Y.G.A. (Make Yarn Great Again)
> Frontend update to fix the build

- benchmark/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate/pom.xml
- pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
> Bump version to 1.2.0

- converter/src/main/java/gov/cms/qpp/conversion/encode/JsonWrapper.java
- converter/src/test/java/gov/cms/qpp/conversion/encode/JsonWrapperTest.java
- JIRA story QPPCT-632.
- Makes date validation more lenient
> date validation fix

- converter/src/main/java/gov/cms/qpp/conversion/encode/JsonWrapper.java
- JIRA story QPPCT-632.
- Address feedback
> Address feedback, optimize

- DEVELOPER.md
- JIRA story QPPCT-638.
- Updated the `Additional Prerequisite Software` section of the `DEVELOPER.md`.
> QPPCT-638: Update development dependency documentation

- benchmark/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate/pom.xml
- pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
> version bump to 1.2.2 for the next release

- tools/bin/docker_deploy.sh
- QPPCT-661
- Change docker_deploy.sh to return failure on an ansible failure
> Docker Script Fix

- .circleci/config.yml
- tools/bin/docker_deploy.sh
- tools/bin/sonarqube.sh
- QPPCT-662
- Change settings to deploy off of builds to `develop` instead of `master` for CircleCI and SonarQube.
> Update Circle and Sonar configs

- .env
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidatorTest.java
- QPPCT-656
- Friendlier formatting for submission end date
- Provide a contact email address for CPC+ inquiries
> QPPCT-656: friendlier CPC submission deadline error message

- benchmark/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureIdValidator.java
- converter/src/test/resources/fixtures/qppct298/cms137v5.xml
- frontend/package.json
- generate/pom.xml
- pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
> Merge stratifier hot fix into master

- benchmark/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureIdValidator.java
- converter/src/test/resources/fixtures/qppct298/cms137v5.xml
- frontend/package.json
- generate/pom.xml
- pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- QPPCT-670
- Change stratifier uuid validation check to be case insensitive.
> Bugfix for stratifier UUID insensitivity

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcMeasureDataValidator.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/CpcMeasureDataValidatorTest.java
- converter/src/test/resources/fixtures/missingSupplementalCodeFile.xml
QPPCT-671 (Fix supplemental data parsing NPE)
This is to merge the hotfix branch to master fixing the above issue.
> Hotfix v1.3.1

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Make error code 52 more clear

- README.md
> Add CPC_END_DATE info to the README.md

- commandline/src/main/resources/logback.xml
> Simplify commandline log output

- rest-api/src/main/resources/logback.xml
> Adds date to log output

- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/QrdaControllerV1.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/exceptions/AuditException.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/AuditService.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/AuditServiceImpl.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/QrdaControllerV1Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/AuditServiceImplTest.java
> Adds Location header to conversion request

- commons/src/main/java/gov/cms/qpp/conversion/model/validation/MeasureConfigs.java
- commons/src/main/java/gov/cms/qpp/conversion/model/validation/SubPopulation.java
- commons/src/main/java/gov/cms/qpp/conversion/util/MeasuredInputStreamSupplier.java
- commons/src/main/java/gov/cms/qpp/conversion/util/StringHelper.java
- converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
- converter/src/main/java/gov/cms/qpp/conversion/decode/ReportingParametersActDecoder.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/AciMeasurePerformedRnREncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/model/Node.java
- converter/src/main/java/gov/cms/qpp/conversion/segmentation/QrdaScope.java
- converter/src/test/java/gov/cms/qpp/conversion/segmentation/QrdaScopeTest.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/AnyOrderActionService.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/model/UnprocessedCpcFileDataTest.java
- QPPCT-715
- reduces code smell
> QPPCT-715: De smell

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Improve error code 32

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- JIRA story QPPCT-733.
- Fixed a typo in our error messages.
> QPPCT-733: occured -> occurred

- converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
- converter/src/test/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoderTest.java
-  QPPCT-743
- ignore NPI for non individual submissions
> QPPCT-743: ignore NPI for non individual submissions

- pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- JIRA story QPPCT-744.
- Specifically adds aws dependencies rather than pulling ALL of them
> Minimize aws dependency

- commons/pom.xml
- converter/pom.xml
- converter/src/test/java/gov/cms/qpp/acceptance/SubmissionIntegrationTest.java
- converter/src/test/java/gov/cms/qpp/conversion/ConversionReportTest.java
- generate/pom.xml
- pom.xml
- rest-api/pom.xml
- rest-api/src/main/java/gov/cms/qpp/conversion/api/RestApiApplication.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/DynamoDbConfig.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/AnyOrderActionService.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/DbServiceImpl.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/InOrderActionService.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/StorageServiceImpl.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/RestApiApplicationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/SpringTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/ExceptionHandlerControllerV1Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/CpcRestIntegrationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/HealthRestIntegrationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/QrdaRestIntegrationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/model/UnprocessedCpcFileDataTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/AnyOrderAsyncActionServiceTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/DbServiceImplTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/InOrderAsyncActionServiceTest.java
- rest-api/src/test/resources/test.properties
- test-commons/pom.xml
- JIRA story QPPCT-580.
- Move to Spring Boot 2.0
- Upgrade several other dependencies
> Spring Boot 2.0

- converter/pom.xml
- JIRA story QPPCT-765.
- Reduces scope of apache httpclient dependency to test
> Reduce scope of httpclient dependency

- rest-api/src/main/resources/application.properties
- JIRA story QPPCT-767.
- Updates spring boot properties to 2.0
> Update properties for spring boot 2.0

- commandline/src/main/java/gov/cms/qpp/conversion/CommandLineMain.java
- commandline/src/main/java/gov/cms/qpp/conversion/CommandLineRunner.java
- commandline/src/test/java/gov/cms/qpp/conversion/CommandLineMainTest.java
- commandline/src/test/java/gov/cms/qpp/conversion/CommandLineRunnerTest.java
- converter/src/main/java/gov/cms/qpp/conversion/Context.java
- converter/src/main/java/gov/cms/qpp/conversion/decode/QrdaDecoderEngine.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/ClinicalDocumentEncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/model/TemplateId.java
- converter/src/test/java/gov/cms/qpp/acceptance/IaSectionValidatorRoundTripTest.java
- converter/src/test/java/gov/cms/qpp/conversion/ContextTest.java
- converter/src/test/java/gov/cms/qpp/conversion/ConverterTest.java
- converter/src/test/java/gov/cms/qpp/conversion/decode/QrdaDecoderEngineTest.java
- converter/src/test/java/gov/cms/qpp/conversion/model/TemplateIdTest.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/ClinicalDocumentValidatorTest.java
- QPPCT-710
- drop insignificant templates
> QPPCT-710: prune insignificant branches

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Fix typo in error code 13

- commandline/pom.xml
- commons/pom.xml
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- commons/src/main/java/gov/cms/qpp/conversion/model/validation/MeasureConfigs.java
- converter/pom.xml
- converter/src/main/java/gov/cms/qpp/conversion/PathSource.java
- converter/src/main/java/gov/cms/qpp/conversion/decode/QrdaDecoder.java
- converter/src/main/java/gov/cms/qpp/conversion/model/validation/SupplementalData.java
- converter/src/test/java/gov/cms/qpp/conversion/encode/JsonWrapperTest.java
- pom.xml
- rest-api/pom.xml
- rest-api/src/main/java/gov/cms/qpp/conversion/api/logging/AttachmentHashPartConverter.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/QrdaServiceImpl.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/ValidationServiceImpl.java
- JIRA story QPPCT-523.
- Adds spotbugs, the continuation of findbugs, to the build process
> Adds Spotbugs to the build process

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- QPPCT-760
- Update **eCQM section** to **measure section**
- Remove **eCQM** in places where it is not needed.
> Error message updates for eCQM

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- JIRA story QPPCT-750.
- Updated error messages to include service center info
> Update error messages 3 and 4 to include service center info

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- QPPCT-756
- Updates error messages 15 through 21 to use **element** instead of **node**
> Update error messages

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Update error message 7

- ERROR_MESSAGES.md
- benchmark/pom.xml
- commandline/pom.xml
- converter/pom.xml
- generate/pom.xml
- pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-commons/src/main/java/gov/cms/qpp/test/enums/EnumContract.java
> Specify maven plugin versions / groups

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Update error message 2

- .circleci/config.yml
> Remove clean phase from circleci

- ERROR_MESSAGES.md
- rest-api/pom.xml
- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/CpcFileControllerV1.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/CpcFileService.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/CpcFileServiceImpl.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/acceptance/CpcApiAcceptance.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/CpcFileControllerV1Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/CpcFileServiceImplTest.java
- QPPCT-741
- added get endpoint for CPC+ QPP
> QPPCT-741: cpc plus qpp get

- .gitattributes
- converter/src/test/java/gov/cms/qpp/TestHelper.java
- converter/src/test/java/gov/cms/qpp/acceptance/ClinicalDocumentRoundTripTest.java
> Fix windows build

- benchmark/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate/pom.xml
- pom.xml
- qpp-data-restoration/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
Merge release branch back to develop.
Adds in the version bump.
> bump version to 1.4.2

- .circleci/config.yml
Fixes chrome install error on the ui_test build step
> add libappindicator3-1 to apt installed packages for chrome install

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Update error code 43

- rest-api/src/test/resources/application.properties
> Copy relevant properties to test application.properties

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Update error code 45

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Update error message 36

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Remove error codes 46 and 47

- .circleci/config.yml
> Remove cmd from docker configuration in circleci

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/AggregateCountEncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/util/DuplicationCheckHelper.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/AggregateCountValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/Checker.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CommonNumeratorDenominatorValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/MeasureDataValidator.java
- converter/src/test/java/gov/cms/qpp/conversion/ScopedConversionTest.java
- converter/src/test/java/gov/cms/qpp/conversion/util/DuplicationCheckHelperTest.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/AggregateCountValidatorTest.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/MeasureDataValidatorTest.java
- QPPCT-753
- Refactors the error message to show the parent element and number of aggregate counts it contains.
- Refactor tests.
> Error Code 8 update

- converter/src/main/java/gov/cms/qpp/conversion/decode/QrdaDecoderEngine.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/AciNumeratorDenominatorEncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/AciSectionEncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/JsonOutputEncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/JsonWrapper.java
- converter/src/main/java/gov/cms/qpp/conversion/model/Node.java
- converter/src/main/java/gov/cms/qpp/conversion/model/error/Detail.java
- converter/src/main/java/gov/cms/qpp/conversion/xml/XmlUtils.java
- converter/src/test/java/gov/cms/qpp/acceptance/ElementLocationTest.java
> Add line numbers to errors

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/DocumentationReference.java
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
- converter/src/test/java/gov/cms/qpp/acceptance/cpc/CpcPlusAcceptanceTest.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidatorTest.java
- converter/src/test/resources/cpc_plus/failure/fixture.json
- QPPCT-812
- Rewording for error code 34
> QPPCT-812: reword error code 34

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- QPPCT-831
- Changed `Measure Performed` to `IA performed measure reference and results` as this is what the IG refers this to be.
- Add the child element that is required which is a `measure performed`. Thus another reason to make the above change.
> Update error message 50

- converter/src/main/java/gov/cms/qpp/conversion/model/Node.java
> Optimize Node#removeChildNode

- .gitignore
> Remove benchmark from .gitignore

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Add link to IG for error code 48

- .github/CODEOWNERS
> Remove Peter and Clyde from CODEOWNERS

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/DocumentationReference.java
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- QPPCT-835
- Modified error message 54 to state this error is for CPC+ submissions and add an IG link.
> Modify error message 54

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Remove error code 60

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Update error code 61

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> Add a link to the IG for error code 59

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
>  Add a pointer to the IG for error code 69

- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate/pom.xml
- pom.xml
- qpp-data-restoration/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- Update develop with the release branch pom updates.
> Release v1.4.4 pom updates

- commons/src/main/java/gov/cms/qpp/conversion/DocumentationReference.java
- JIRA story QPPCT-958.
- Update documentation references
> Update documentation references

- .github/CONTRIBUTING.md
- after-clone.sh
- JIRA story QPPCT-963.
- Adds a script you run after cloning to install git secrets
> Git secrets

- .circleci/config.yml
> Use new sonarscanner distribution

- sample-files/2018/CPCPlus_StructurallyCorrectAddressEx1_SampleQRDA-III.xml
- sample-files/2018/ComprehensivePrimaryCareSampleQRDA-III_SDE.xml
- sample-files/2018/MIPS_GROUP_QRDA_III_ACI_IA_Sample1.xml
- A file for MIPS, CPC Plus and one comprehensive CPC Plus file.
> WIP: Update some 2018 sample files

- .circleci/config.yml
- README.md
- commandline/pom.xml
- pom.xml
- tools/bin/sonarqube.sh
- JIRA story QPPCT-989
- Told the surefire plugin to avoid using the system class loader
> QPPCT-989: surefire class loader workaround

- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/CpcFileControllerV1.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Details.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Metadata.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/model/DetailsTest.java
> Fix dynamodb issue

- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/CpcFileControllerV1.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Metadata.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/CpcFileControllerV1Test.java
> Adds Metadata version to restrict report endpoint

- rest-api/pom.xml
> Spring updates

- pom.xml
- JIRA story QPPCT-999.
- Update AWS
> Aws update

- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureSectionValidator.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureSectionValidatorTest.java
- converter/src/test/resources/cpc_plus/failure/fixture.json
- QPPCT-871
- Fixed Measure Groups for CPC+ Groupings
> Fix validation and tests

- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcPerformancePeriodValidation.java
- rest-api/pom.xml
> Add spring devtools

- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureIdValidator.java
- JIRA story QPPCT-997.
- Adds strata null check
> Fix NPE: eCQI sample files do not validate

- converter/src/main/java/gov/cms/qpp/conversion/Converter.java
- JIRA story QPPCT-1010.
- Temporary fix for QPPCT-1008
> Temporary fix for 1008

- rest-api/src/main/java/gov/cms/qpp/conversion/api/helper/MetadataHelper.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Metadata.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/DbServiceImpl.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/acceptance/CpcApiAcceptance.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/CpcFileControllerV1Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/QrdaControllerV1Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/helper/MetadataHelperTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/model/MetadataTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/model/UnprocessedCpcFileDataTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/AuditServiceImplTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/CpcFileServiceImplTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/DbServiceImplTest.java
- JIRA story QPPCT-1007.
- Fix metadata version problems
> Fix metadata version problems

- converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/ClinicalDocumentEncoder.java
- converter/src/test/java/gov/cms/qpp/acceptance/CpcPlusRoundTripTest.java
- converter/src/test/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoderTest.java
- JIRA story QPPCT-1012
- Revamp top level attributes for CPC+ submissions
> QPPCT-1012: APM support

- commons/src/main/java/gov/cms/qpp/conversion/model/validation/MeasureConfigs.java
- converter/src/main/java/gov/cms/qpp/conversion/util/MeasureConfigHelper.java
- JIRA story QPPCT-1016.
- Fix UUID case sensitivity problem
> Fix UUID case sensitivity

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/Checker.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
- converter/src/test/java/gov/cms/qpp/acceptance/CpcPlusRoundTripTest.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidatorTest.java
- QPPCT-909 npi / tin existence check
- Added TIN and NPI existence checks for CPC+ submissions
> QPPCT-909: CPC+ NPI TIN check

- .dockerignore
- JIRA 
- added .dockerignore to limit what's copied to container
> only copy what's necessary to satisfy Dockerfile

- converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
- converter/src/test/java/gov/cms/qpp/acceptance/CpcPlusRoundTripTest.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidatorTest.java
> remove apm npi validation

- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qpp-data-restoration/pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
> bump to version 2.0.0

- converter/src/main/java/gov/cms/qpp/conversion/ConversionReport.java
- converter/src/main/java/gov/cms/qpp/conversion/Converter.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/JsonOutputEncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/model/error/ValidationResult.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/Checker.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CommonNumeratorDenominatorValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureIdValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/MeasureDataValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/MipsQualityMeasureIdValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/NodeValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/QrdaValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/ReportingParametersActValidator.java
- converter/src/test/java/gov/cms/qpp/conversion/stubs/TestDefaultValidator.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v2/QrdaControllerV2.java
- Adds JavaDoc to files touched in the story branch
- QPPCT-1019.
- Added JavaDoc
- [-] New unit tests written to cover new functionality.
- [-] Updated documentation (`README.md`, etc.) depending if the changes require it.
> QPPCT-1019 JAVADOC

- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v2/QrdaControllerV2.java
- Fixes #844.
- JIRA story QPPCT-1021.
> Fix metadata_holder in v2 endpoint response

- rest-api/pom.xml
- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/SkeletalQrdaController.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v2/QrdaControllerV2.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/QrdaControllerV1Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/model/CpcValidationInfoMapTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/model/CpcValidationInfoTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/StorageServiceImplTest.java
- Full unit test coverage.
- JIRA story QPPCT-1004.
- added unit tests to complete coverage of class touched in the body of work.
- added junit dependencies to the pom for eclipse compatibility.
> Story 1004

- ERROR_MESSAGES.md
- commandline/src/main/java/gov/cms/qpp/conversion/ConversionFileWriterWrapper.java
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
- converter/src/main/java/gov/cms/qpp/conversion/Context.java
- converter/src/main/java/gov/cms/qpp/conversion/Converter.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/NodeValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/pii/MissingPiiValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/pii/PiiValidator.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidatorTest.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/SkeletalQrdaController.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidator.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/CpcValidationInfo.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/CpcValidationInfoMap.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/QrdaServiceImpl.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/StorageServiceImpl.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidatorTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/model/CpcValidationInfoMapTest.java
> PII validation logic

- converter/src/main/java/gov/cms/qpp/conversion/encode/JsonWrapper.java
- converter/src/test/java/gov/cms/qpp/conversion/encode/JsonWrapperTest.java
> Fix new line qpp problem

- converter/src/main/java/gov/cms/qpp/conversion/Context.java
- converter/src/main/java/gov/cms/qpp/conversion/ConversionReport.java
- converter/src/main/java/gov/cms/qpp/conversion/Converter.java
- converter/src/main/java/gov/cms/qpp/conversion/correlation/PathCorrelator.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/JsonWrapper.java
- converter/src/test/java/gov/cms/qpp/acceptance/AciMeasurePerformedRoundTripTest.java
- converter/src/test/java/gov/cms/qpp/conversion/ConversionReportTest.java
- converter/src/test/java/gov/cms/qpp/conversion/ScopedConversionTest.java
- converter/src/test/java/gov/cms/qpp/conversion/correlation/QrdaQppAssociationTest.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/QrdaControllerV1.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v2/QrdaControllerV2.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/ValidationServiceImpl.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/QrdaControllerV1Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/QrdaServiceImplTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/ValidationServiceImplTest.java
> Fix NPE from new meta changes + validation service

- converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
- converter/src/test/java/gov/cms/qpp/acceptance/CpcPlusRoundTripTest.java
- rest-api/pom.xml
- rest-api/src/main/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidator.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/CpcValidationInfoMap.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/model/CpcValidationInfoMapTest.java
- Swaps the NPI with APM
- [n/a ] Updated documentation (`README.md`, etc.) depending if the changes require it.
> Fix npi issue

- commons/src/main/java/gov/cms/qpp/conversion/model/error/ErrorCode.java
> TIN instead of PII

- ERROR_MESSAGES.md
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- converter/src/main/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoder.java
- converter/src/test/java/gov/cms/qpp/acceptance/QualityMeasureIdRoundTripTest.java
- converter/src/test/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoderTest.java
- converter/src/test/resources/negative/junk_in_quality_measure.xml
- frontend/package.json
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qpp-data-restoration/pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- Merge release v2.1.1 into master
> Release v2.1.1

- pom.xml
- tools/ansible/conversion_playbook.yml
- makes use of the Nexus repo manager
- specified Nexus repo for dependencies and plugins
> use repo manager

- converter/src/main/java/gov/cms/qpp/conversion/encode/JsonWrapper.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/JacksonConfig.java
> Jackson config

- .gitignore
- JIRA story QPPSF-5021.
- Gitignore updates for visualstudiocode and bin directories
> Gitignore updates for VSC and bin dir

- converter/src/main/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureSectionValidator.java
- converter/src/test/java/gov/cms/qpp/acceptance/QualityMeasureIdRoundTripTest.java
- converter/src/test/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoderTest.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureSectionValidatorTest.java
- converter/src/test/resources/correctMultiToSinglePerfMeasureExample.xml
- converter/src/test/resources/negative/wrongSubPopulationsMeasure135.xml
- qrda-files/valid-QRDA-III-latest.xml
- QPPSF-4885
- Adds more Multi to Single Performance Rate conversions and some test coverage.
- Changes Outcome Measure Requirements to have at least two measures (CMS122 and CMS165).
> eCQM Validation Updates

- commons/src/main/java/gov/cms/qpp/conversion/DocumentationReference.java
- QPPSF-5134
- Updates the Implementation guide reference and it's pages
> Update Implementation Guide references

- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
- Fixes a build issue that occurs from find bugs
> Fix build bug with non-called method

- commandline/src/test/resources/measures-data.json
- commons/src/main/resources/measures-data.json
- converter/src/main/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/util/MeasureConfigHelper.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/Checker.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureIdValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidator.java
- converter/src/test/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoderTest.java
- converter/src/test/resources/measureGlossary.json
- sample-files/2019/measure370Example.xml
- QPPSF-5272
- Measure 370 was changed to an edge case scenario where measure would start a single performance rate and convert into a multi performance rate with one of the populations fields defaulting to 0.
> Measure 370 Conversion Updates

- commandline/src/test/resources/measures-data.json
- commons/src/main/resources/measures-data.json
- Fixes CMS22 as the UUIDs were being skipped in `app-measures-data`
> Update UUID measures

- converter/pom.xml
- generate/pom.xml
- pom.xml
- rest-api/pom.xml
- Fixes #_.
- JIRA story QPPSF-5394.
Remove dependencies from properties sections of maven config to make sure github can accurately find vulnerabilities.
> Localize dependencies

- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/CpcValidationInfoMap.java
- Fixes map initialization for the APM to TIN/NPI map list.
> APM to TIN->NPI map fix

- pom.xml
- AWS Version Added to parent pom
> AWS Version Added

- sample-files/2019/CMS22v7InvalidMeasureUuid.xml
- sample-files/2019/CMS22v7InvalidPopulationUuids.xml
- sample-files/2019/CMS22v7MeasureExample.xml
- Adds sample files for CMS22v7
> Add sample files for CMS22v7

- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/DynamoDbConfig.java
- Change save behavior as DynamoDBMapper now requires it in order to save in dynamo.
> CPC+ Endpoint Timeout.

- converter/src/main/java/gov/cms/qpp/conversion/encode/MeasureDataEncoder.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/CpcValidationInfoMap.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/QrdaService.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/QrdaServiceImpl.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/StorageServiceImpl.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/acceptance/CpcApiAcceptance.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/QrdaControllerV1Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v2/QrdaControllerV2Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v2/ZipControllerTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/DbServiceImplTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/QrdaServiceImplTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/ValidationServiceImplTest.java
- test-commons/src/main/java/gov/cms/qpp/test/net/InternetExecutionCondition.java
- test-commons/src/main/java/gov/cms/qpp/test/net/InternetTest.java
- JIRA story QPPSF-5490.
- Rewrite InternetTest framework
> Fix InternetTest framework

- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/DbServiceImplTest.java
- Forgot to add this to the Dynamo query test page.
> Fix dynamo tests

- converter/src/test/java/gov/cms/qpp/acceptance/SubmissionIntegrationTest.java
- rest-api/pom.xml
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v2/ZipControllerTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/QrdaRestIntegrationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/QrdaRestv2IntegrationTest.java
- rest-api/src/test/resources/test.properties
Reverts CMSgov/qpp-conversion-tool#931
> Revert "Fix submission validation testing url"

- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Constants.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/CpcValidationInfoMap.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/QrdaService.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/QrdaServiceImpl.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/StorageService.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/StorageServiceImpl.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/QrdaControllerV1Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v2/QrdaControllerV2Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v2/ZipControllerTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidatorTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/model/CpcValidationInfoMapTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/QrdaServiceImplTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/StorageServiceImplTest.java
Reverts CMSgov/qpp-conversion-tool#926
> Revert "Download CMS validation file from FMS"

- converter/src/main/java/gov/cms/qpp/conversion/encode/MeasureDataEncoder.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/CpcValidationInfoMap.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/QrdaService.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/QrdaServiceImpl.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/StorageServiceImpl.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/acceptance/CpcApiAcceptance.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/QrdaControllerV1Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v2/QrdaControllerV2Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v2/ZipControllerTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/DbServiceImplTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/QrdaServiceImplTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/ValidationServiceImplTest.java
- test-commons/src/main/java/gov/cms/qpp/test/net/InternetExecutionCondition.java
- test-commons/src/main/java/gov/cms/qpp/test/net/InternetTest.java
> Remerge QPPSF-5490

- pom.xml
- JIRA story QPPSF-5531.
- Adds new offline build profile (-P offline)
> Offline-mode build profile

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- frontend/package.json
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qpp-data-restoration/pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
As the title states, a pom version update.
> Version update for release v3.0.0

- pom.xml
- test-commons/src/main/java/gov/cms/qpp/test/net/InternetExecutionCondition.java
- JIRA story QPPSF-5589.
- Update surefire to fix junit tagging
- Fix bug in internet connected tests
> Update surefire, fix internet connected tests

- rest-api/pom.xml
- JIRA story QPPSF-5602.
- Removed a duplicate dependency declaration in rest-api/pom.xml
> Fix duplicate dependency warning

- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
- converter/src/main/java/gov/cms/qpp/conversion/decode/QrdaDecoder.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/QualityMeasureIdEncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/model/validation/ApmEntityIds.java
- converter/src/main/java/gov/cms/qpp/conversion/util/MeasureConfigHelper.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureSectionValidator.java
- converter/src/test/java/gov/cms/qpp/acceptance/ClinicalDocumentExtensionTest.java
- converter/src/test/java/gov/cms/qpp/conversion/decode/MeasurePerformedDecoderTest.java
- converter/src/test/java/gov/cms/qpp/conversion/decode/PerformanceRateProportionMeasureDecoderTest.java
- converter/src/test/java/gov/cms/qpp/conversion/decode/SupplementalDataEthnicityDecoderTest.java
- converter/src/test/java/gov/cms/qpp/conversion/decode/SupplementalDataPayerDecoderTest.java
- converter/src/test/java/gov/cms/qpp/conversion/decode/SupplementalDataRaceDecoderTest.java
- converter/src/test/java/gov/cms/qpp/conversion/decode/SupplementalDataSexDecoderTest.java
- pom.xml
- rest-api/pom.xml
- rest-api/src/test/java/gov/cms/qpp/conversion/api/acceptance/CpcApiAcceptance.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/helper/JwtTestHelper.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/CpcRestIntegrationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/HealthRestIntegrationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/QrdaRestIntegrationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/QrdaRestv2IntegrationTest.java
- test-commons/pom.xml
- JIRA story QPPSF-5651 QPPSF-5652
- Refactor dependencies
- Update dependencies
- Specifically update jjwt dependency
> Dependency updates, cleanup

- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/DbServiceImpl.java
- https://jira.cms.gov/browse/QPPSF-5592
- Changes the limit from 10 to 4. 4 was picked due to having a limit of 128 files found which was closest to what limit we had before.
> CPC+ Retrieve File List Limit

- commons/pom.xml
- pom.xml
- QPPSF-5795
- These are bug fixes for develop as the rest api is currently broken.
> Fix for build failures

- .github/workflows/feature-build.yml
There is no ticket associated with this one. The changes here are to support github action based build in CT.
> Enable Github Actions

- .github/workflows/ecr-publish.yml
- Add GitHub action to publish docker build to AWS ECR
> added ecr-publish.yml GitHub action config

- .github/workflows/draft-release.yml
- .github/workflows/ecr-publish.yml
- Update conditions for each env in the ecr-publish.yml
- Remove condition in draft-release.yml
> Feature/modify docker publish GitHub build conditions

- tools/docker/docker-artifacts/newrelic/newrelic.yml
- Fixes #_.
Related: https://confluence.cms.gov/pages/viewpage.action?spaceKey=NR&title=FedRamp+Configuration+Changes+Details
We have 3 days to convert to the updated New Relic url to keep logged data to going to a FedRamped URL. This PR should encapsulate the bulk of the work.
-
-
> Use FedRamped NewRelic URL

- .github/workflows/draft-release.yml
- .github/workflows/ecr-publish.yml
- .github/workflows/feature-build.yml
- .github/workflows/git-leaks.yml
- .gitleaks.toml
- Adding Gitleaks GitHub Action to provide a solution to automatically run a gitleaks scan on push or pull git requests.
- Added .gitleaks.toml to the base directory
- Added git-leaks.yml to .github/workflows directory
> added git-leaks gh action config

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/DocumentationReference.java
- converter/src/test/resources/cpc_plus/failure/2020/CPCPlus-UUID-Updates-Failures.xml
- converter/src/test/resources/cpc_plus/success/2020/CPCPlus_2020-Guid-Updates.xml
- sample-files/2020/CPCPlus-UUID-Updates-Failures.xml
Add failure sample file and update the error message to display the proper year.
> QPPSF-6544: Sample files and error message update

- .github/workflows/ci-build.yml
- .github/workflows/draft-release.yml
- .github/workflows/ecr-publish.yml
- Updated ci-build.yml to trigger the CI Suite after any push
> Update ci-build.yml to include all push events

- .github/workflows/ecr-publish.yml
- JIRA story QPPSF-6618
- Modified the Slack message
- Added an env tag to the name
- Testing a failed build
> QPPSF-6618: Cleanup ecr-deploy slack notification configuration

- .github/workflows/ci-build.yml
- JIRA story QPPSF-6618
- Added maven dependency caching support to speed up the build and tests
> QPPSF-6618: Add caching support for maven builds

- .github/workflows/ecr-publish.yml
- JIRA story QPPSF-6618
- Modify docker tags - qppsf/conversion-tool/${env}:latest
> QPPSF-6618: Modify ECR Docker tags

- infrastructure/terraform/dev/main.tf
- infrastructure/terraform/dev/variables.tf
- infrastructure/terraform/modules/s3.tf
- infrastructure/terraform/modules/ssm.tf
- infrastructure/terraform/modules/templates/conversion_tool_task_def.tpl
- infrastructure/terraform/secure/README.md
- infrastructure/terraform/secure/secret-template.tf
- infrastructure/terraform/secure/variables.tf
- QPPSF-6654: adds the org name for RTI. This value is likely to need to be changed manually as the JWT tokens haven't been created yet. However, we will need this env variable when it is created.
> Add SSM env variable

- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/SecurityConfig.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/security/JwtAuthorizationFilter.java
> Auth logging for debugging dev

- infrastructure/terraform/modules/templates/conversion_tool_task_def.tpl
> adding RTI_ORG_NAME parameter to the task definition

- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/SecurityConfig.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/security/JwtAuthorizationFilter.java
This reverts commit acbb0dbf4cec7b79d67a01f133e81261f3273b14.
- Fixes #_.
-
-
> Revert "Auth logging for debugging dev"

- converter/src/main/java/gov/cms/qpp/conversion/util/MeasureConfigHelper.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcQualityMeasureIdValidator.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidator.java
- QPPSF-6987
- Fixes the measure 370 bug to allow proper validation.
> Fix measure 370 to use the measure id over the CMS identifier

- ERROR_MESSAGES.md
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ProblemCode.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidator.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/QrdaServiceImpl.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidatorTest.java
- Update warning messaging
- Fix null scenarios as they were defined incorrectly and fix tests.
> QPPSF-7066: warning updates

- converter/src/test/java/gov/cms/qpp/acceptance/cpc/CpcPlusAcceptanceTest.java
- converter/src/test/resources/cpc_plus/success/2020/warnings/CPCPlus_2020-Warning-IA-Section.xml
- converter/src/test/resources/cpc_plus/success/2020/warnings/CPCPlus_2020-Warning-PI-Section.xml
-  Add test case scnearios for 2020
> QPPSF-6917: IA And PI warning

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qpp-data-restoration/pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
> Release 4.3.3

- converter/src/main/java/gov/cms/qpp/conversion/encode/ClinicalDocumentEncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/PiSectionEncoder.java
> QPPSF-7908: Fix PCF encoding to exclude practiceId

- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/StorageServiceImpl.java
- Fixing a parameter store issue with the APM/TIN/NPI file to be disabled properly
> Fix Parameter URL intake for APM/TIN/NPI parameter store file

- .github/workflows/ecr-publish.yml
- isg-okr.properties
QPPSF-8422, QPPSF-8095
- Added conversion-tool ecs deployment steps in github-actions
- Added okr metrics for conversion-tool part of github-actions in the workflow
- Added isg-okr-properties file which has to be updated(manually) for every CT release with required properties for git-hub workflow to read from
> QPPSF-8422, QPPSF-8095 - Added okr metrics, CD steps for conversion-tool

- .github/workflows/ecr-publish.yml
- isg-okr.properties
- Fixes #_.
QPPSF-8095
- Changed the same identifier name, which has been used in the workflow scope
> QPPSF-8095, fixed identifier 'read_properties' error in the workflow

- infrastructure/terraform/dev/github-user.tf
**Fixes:**
Added missing iam permissions for github-actions-ecr user role-policy
- Added missing iam permissions for github-actions-ecr user role-policy
> Added missing iam permissions for user iam role-policy

- .github/workflows/ecr-publish.yml
- Fixes #_
An extra quote was identified in the workflow step, which is causing the workflow to fail
- Removed extra quote in okr step github workflow
> Fixed issue with okr step in github workflow 

- .github/workflows/ecr-publish.yml
- OKR Prod/DevPre step configuration issue.
> Fixed issue with okr step (#1129)

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- commons/src/main/resources/measures-data.json
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qpp-data-restoration/pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
> Update poms to 15.3.0

- rest-api/src/main/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidator.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/TinNpiCombination.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidatorTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/model/TinNpiCombinationTest.java
- https://jira.cms.gov/browse/QPPSF-8829
- Add checks for missing Tin/Npi combinations and tests to cover
> QPPSF-8829: Participation File Validation Update

- infrastructure/terraform/modules/alb.tf
- infrastructure/terraform/modules/ecs.tf
- Fixes #_.
QPPSF-8849
- *Removed non-ssl configuration from terraform modules(alb & ecs)*
> QPPSF-8849, ssl infrastructure tf changes for impl

- mvn-entrypoint.sh
- updates mvn-entrypoint.sh with #!/bin/bash
-
> Update bash script

- .github/workflows/ecr-publish.yml
> moved okr steps

- .github/workflows/ecr-publish.yml
> Release v 16.2.0

- commons/src/main/resources/measures-data.json
- rest-api/src/main/resources/application.properties
> Add ssl spring boot changes back

- commons/src/main/java/gov/cms/qpp/conversion/model/error/ProblemCode.java
- converter/src/main/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidator.java
- converter/src/test/java/gov/cms/qpp/acceptance/ReportingParametersActRoundTripTest.java
- converter/src/test/java/gov/cms/qpp/acceptance/XpathJsonPathComparisonTest.java
- converter/src/test/java/gov/cms/qpp/conversion/validate/CpcClinicalDocumentValidatorTest.java
- qrda-files/valid-QRDA-III-latest.xml
- rest-api/src/main/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidator.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/internal/pii/SpecPiiValidatorTest.java
- https://jira.cms.gov/browse/QPPSF-9315
- Updates Warning message 80 with proper verbiage by program type
- Updates error message 68 with proper verbiage by program type
> QPPSF-9315: Warning message update

- infrastructure/terraform/modules/iam.tf
- Fixes #_.
QPPSF-9852
- *Modified IAM role names in module as per Environment*
> QPPSF-9852, Modified iam-role names in module as per Env

- converter/src/test/java/gov/cms/qpp/conversion/encode/JsonWrapperTest.java
- pom.xml
- Snyk updates to jackson but also fixes unit tests
-
> Update jackson libraries and fix broken unit tests

- Dockerfile
- README.md
- rest-api/pom.xml
- Spring Vulnerability Updates
- Docker image build fixes.
> QPPSF-9980 & QPPSF-9915

- generate-race-cpcplus/pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- Updates Spring dependencies
- Spring security update for a major vulnerability.
> QPPSF-10138: Dependency updates

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qpp-data-restoration/pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
> Update Release in Dev

- acceptance-tests/pom.xml
- pom.xml
- rest-api/pom.xml
- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/SwaggerConfig.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/SkeletalQrdaController.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/CpcFileControllerV1.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/controllers/v1/PcfFileControllerV1.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/ExceptionHandlerControllerV1Test.java
- Update dependencies and fix tests
-
-
> QPPSF-10177: Spring Starter

- infrastructure/terraform/dev/github-user.tf
- infrastructure/terraform/dev/main.tf
- infrastructure/terraform/dev/variables.tf
- infrastructure/terraform/modules/ssm.tf
- infrastructure/terraform/modules/variables.tf
- qppsfct-copy-certs.sh
- Fixes #_.
QPPSF-9833
- *Added iam user permissions for ACM*
- _Added Cert ARN to SSM Parameter_
- _Modified bash script `qppsfct-copy-certs.sh` for certs export from ACM_
> QPPSF-9833, CERT export automation for end-to-end encryption

- converter/src/main/java/gov/cms/qpp/conversion/validate/QualityMeasureIdValidator.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/SecurityConfig.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/QrdaServiceImpl.java
- The JWT token signature was not changed as Kong handles the actual signature of the token. Any validation we do on the token is for information in the token and not the actual signing of the token. More details in the comment section of the ticket https://jira.cms.gov/browse/QPPSF-10196 @peter-stancic
- Snyk fixes from the ticket specified.
> QPPSF-10196 Snyk Fixes

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- commons/src/main/resources/measures-data.json
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qpp-data-restoration/pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
- Bump version 18.3.0 to develop
> Bump version 18.3.0

- infrastructure/dynamo-db-backp-notifier/ddb-backup-notifier.tf
- infrastructure/dynamo-db-backp-notifier/dynamo-db-bckup-notifier.py
- infrastructure/ecr-notification-lambda/ecr-scan-notification.tf
- infrastructure/ecs-pagerduty-alert/ecs-pagerduty-alerts.tf
- Fixes #_.
QPPSF-10495 
- *Updated Tf code base Lambda functions to use Python version 3.9*
> QPPSF-10495, Devops Python Lambda Version Upgrade for CT

- infrastructure/terraform/modules/kinesis-lambda.tf
Upgrades Lambda function to version 14 from previous version 12
- Updated lambda terraform module version to node 14
> [QPPSF-10833] Devops, Lambda function nodejs version upgrade

- infrastructure/terraform/modules/ecs.tf
- infrastructure/terraform/modules/iam.tf
- infrastructure/terraform/modules/templates/ecs_task_execution_policy.tpl
- Fixes #_.
-QPPSF-10683_
- *Create ned IAM task execution role iam and policy in the appropriate path and permission boundary*
- *Removed Old iam roles and policies in Tf code*
- *Updated policy with kms resources*
> [QPPSF-10683] Replace old ECS task execution iam role & policy

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qpp-data-restoration/pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
> CT v19.5.0

- rest-api/pom.xml
> QPPSF-10924: Snakeyaml Update

- .github/workflows/ecr-publish.yml
- qppsfct-copy-certs.sh
- Fixes #_.
QPPSF-11403
QPPSF-11270
- *Fix invalid format error when using `$GITHUB_OUTPUT ` output parameter*
- *Fix unused user IAM credentials being used inside bash script*
> [QPPSF-11403] [QPPSF-11270] fixes GHA errors in the workflow

- .github/workflows/ecr-publish.yml
- Fixes #_.
QPPSF-11270
- *Corrected image name output syntax when output is redirected to environment variable*
> QPPSF-11270 - fix missing output for image name

- buildspec.yml
- Fixes #_.
Adhoc
- *Added slack channel in variables, moved from parameter-store*
> fix slack parameter in buildspec

- commons/pom.xml
- test-commons/pom.xml
> QPPSF-11952: Update json-smart

- pom.xml
- rest-api/pom.xml
- Update Spring Web MvC to fix Security issues.
> QPPSF-11951: Spring Web MvC Update

- Dockerfile
- Update docker image for security purposes
> QPPSF-12004: Update to use official docker image

- infrastructure/ecs-pagerduty-alert/ecs-pgduty-alerts.py
- infrastructure/terraform/modules/newrelic/alert-policies.tf
- Fixes #_.
- JIRA story: https://jira.cms.gov/browse/QPPSF-11610.
-
-
> QPPSF-11610: Updated Pagerduty endpoint with Splunk-On call endpoint.

- converter/pom.xml
- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/SecurityConfig.java
> [QPPSE-708] Security updates

- acceptance-tests/pom.xml
- generate/pom.xml
- pom.xml
- rest-api/pom.xml
> QPPSE-884: Update dependencies for security

- converter/src/main/java/gov/cms/qpp/conversion/decode/ClinicalDocumentDecoder.java
- A small spot bug's issue with code duplication. A refactored function was duplicated and is now removed.
> QPPSE-910: MVP & Subgroup Additional Fix

- commons/pom.xml
- commons/src/main/resources/measures-data.json
- Temporarily update measures data manually and comment out measure-data update script until QPPSE-1513 is fixed.
> QPPSE-1512: Manual update of measure-data

- buildspec.yml
- upload-part-file.sh
- Updates new script to download from s3, format and upload the participation file into s3.
> [QPPSE-266]: Participation File Automation

- buildspec.yml
- JIRA story QPPSE-1667.
- corrections to buildspec.yml for post_build logic to allow correct status posting, including to Slack
-
-
- [ x ] All JUnit tests pass (`mvn clean verify`).
> Correct logic for post_build 

- infrastructure/terraform/modules/ecr.tf
> [DEVOPS][CT] [QPPSE-1814] Set ECR Lifecycle policy 

- .github/workflows/ci-build.yml
- commandline/src/test/java/gov/cms/qpp/conversion/CommandLineMainTest.java
- commandline/src/test/java/gov/cms/qpp/conversion/CommandLineRunnerTest.java
- commons/src/main/resources/measures-data.json
- commons/src/test/java/gov/cms/qpp/conversion/util/EnvironmentHelperTest.java
- converter/src/test/java/gov/cms/qpp/acceptance/AutoDetectQrdaTest.java
- converter/src/test/java/gov/cms/qpp/conversion/ConversionReportTest.java
- converter/src/test/java/gov/cms/qpp/conversion/correlation/QrdaQppAssociationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/RestApiApplicationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/HealthRestIntegrationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/QrdaRestIntegrationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/integration/QrdaRestv2IntegrationTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/services/internal/ValidationServiceImplTest.java
- sample-files/2023/MultiStrata_SinglePerformanceRate-sample.xml
- Fixed Unit Test failures on CI pipeline and added tests back that was removed due to Unit Test failures part of https://github.com/CMSgov/qpp-conversion-tool/pull/1386
> [QPPSE-1516] Fix Unit Test failures on CI pipeline and add tests back that was removed before

- ERROR_MESSAGES.md
- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- commons/src/main/java/gov/cms/qpp/conversion/model/error/ProblemCode.java
- commons/src/main/resources/measures-data.json
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
> Release v2023.6.1

- converter/src/main/java/gov/cms/qpp/conversion/model/error/Detail.java
- converter/src/test/java/gov/cms/qpp/conversion/model/error/DetailTest.java
- Fixed when submission api returns errors as string instead of Detail class/object
- https://jira.cms.gov/browse/QPPSE-1728
> QPPSE-1728: Updated Detail component to accept string errors from submission api

- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/RequestLoggingFilterConfig.java
- rest-api/src/main/resources/logback.xml
- Adds HTTP request and response logs for additional troubleshooting
- HTTP log will look like this.
```Before request [POST /, headers=[accept:\"application/vnd.qpp.cms.gov.v2+json\", user-agent:\"PostmanRuntime/7.39.0\", host:\"localhost:8080\", accept-encoding:\"gzip, deflate, br\", connection:\"keep-alive\", content-length:\"229627\", Content-Type:\"multipart/form-data;boundary=--------------------------190366961698014722609788;charset=UTF-8\"]]"```
- https://jira.cms.gov/browse/QPPSE-312
> QPPSE-312: Added spring boot http logging

- rest-api/pom.xml
- Fixes Snyk security finding.
- JIRA story: https://jira.cms.gov/browse/QPPA-9297.
- spring-boot-starter-security dependency version bump
> QPPA-9297: Updates spring-boot-starter-security dependency to v3.1.11

- rest-api/pom.xml
- Fixes: Snyk Issue
- JIRA story: https://jira.cms.gov/browse/QPPA-9296
- Upgrade to org.apache.tomcat.embed:tomcat-embed-core@9.0.90
> QPPA-9296: update tomcat version

- commons/src/main/resources/measures-data.json
> QPPSE-2463: Adding latest measures data

- commandline/src/test/resources/measures-data.json
- commons/src/main/resources/measures-data.json
- pom.xml
- Fixes #_.
- JIRA story QPPA-9349, QPPA-9453.
- Fixes security vulnerabilities with previous versions
> QPPA-9349, QPPA-9453: Update packages for security

- tools/scripts/format-participation-file.py
- tools/scripts/retrieve-fms-file.py
- Downloaded the pariticipation file from FMS, extracted the required information, created the respective files and uploaded it to S3 bucket.  And updated the scripts with latest changes as well.
> QPPSE-2004: Added participation file to S3 and updated the scripts

- pom.xml
- Fixes QPPA-9684
- JIRA story https://jira.cms.gov/browse/QPPA-9684
fix snyk issue
> QPPA-9684: fix snyk issue

- commons/src/main/resources/measures-data.json
- pom.xml
- rest-api/pom.xml
- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/SecurityConfig.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/logging/AttachmentHashPartConverter.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/security/JwtAuthorizationFilter.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/QrdaServiceImpl.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/services/internal/ValidationServiceImpl.java
- rest-api/src/main/resources/logback.xml
- rest-api/src/test/java/gov/cms/qpp/conversion/api/controllers/v1/ExceptionHandlerControllerV1Test.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/logging/AttachmentHashPartConverterTest.java
- rest-api/src/test/java/gov/cms/qpp/conversion/api/security/JwtAuthorizationFilterTest.java
- test-commons/pom.xml
- test-commons/src/main/java/gov/cms/qpp/test/logging/LoggerContract.java
- Upgraded Spring Web from 5.x to 6.x and related dependencies
> QPPSE-2333: Upgrade Spring Web from 5.x to 6.x and its related dependencies

- commons/src/main/java/gov/cms/qpp/conversion/model/error/ProblemCode.java
- Updated phone number to include area code and changed to TRS number
- https://jira.cms.gov/browse/QPPSE-2999
> QPPSE-3273: Updated phone number to include area code and changed to TRS number

- rest-api/src/main/resources/application.properties
- JIRA story: https://jira.cms.gov/browse/QPPA-9858
- Explicitly sets sun.io.useCanonCaches to false as best practice to resolve critical tomcat vulnerability - https://www.cve.org/CVERecord?id=CVE-2024-50379
> QPPA-9858: Resolve tomcat vulnerability CVE-2024-50379

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- rest-api/src/main/resources/application.properties
- test-commons/pom.xml
- test-coverage/pom.xml
Bump master to v2024.2.6
Bump master to v2024.2.6
> Release v2024.2.6 into master

- commons/src/main/resources/measures-data.json
- converter/src/test/resources/app/2024/App1-ApmEntity-Qrda-III.xml
- converter/src/test/resources/app/2024/App1-Group-QRDA-III.xml
- converter/src/test/resources/app/2024/App1-Indv-QRDA-III.xml
- Fixed some files for testing error codes and retrieved latest measures data.
- https://jira.cms.gov/browse/QPPSE-3000
> QPPSE-3000: Fix files for testing error codes

- .github/workflows/checkov-tf.txt
- .github/workflows/codebuild-trigger-dev.yml
- .github/workflows/codebuild-trigger-impl.yml
- buildspec/build_deploy.yaml
* Triggering codebuild automatically
* https://jira.cms.gov/browse/QPPA-9810
- Fixes #_.
-
-
> testing auto trigger

- README.md
- tools/docker/docker-artifacts/newrelic/newrelic.yml
update new relic agent to version 8.18.0
update new relic agent to version 8.18.0
> QPPA-9749: update new relic agent

- rest-api/pom.xml
- JIRA story - https://jira.cms.gov/browse/QPPA-10241
- Updated spring-boot dependencies to resolve tomcat-embed-core vulnerability
> QPPA-10241: Update spring-boot packages to clear vulnerability

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
- JIRA story: https://jira.cms.gov/browse/QPPA-10257
> QPPA-10257: update conversion tool version to 2024.2.9

- pom.xml
- JIRA story - https://jira.cms.gov/browse/QPPA-10210
> QPPA-10210: updates spotbugs-maven-plugin to v4.7.3.6

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
- JIRA story https://jira.cms.gov/browse/QPPA-10261
> QPPA-10261: Update release version to v2024.2.10

- pom.xml
- Fixes #_.
- JIRA story [QPPA-10212](https://jira.cms.gov/browse/QPPA-10212).
- bumped mvn-compiler-plugin to 3.14.0
> QPPA-10212: Updated mvn-compiler-plugin to 3.14.0

- acceptance-tests/pom.xml
- pom.xml
- Fixes #_.
- JIRA story [QPPA-10213](https://jira.cms.gov/browse/QPPA-10213).
- bumped mvn-compiler-plugin to 3.14.0
> QPPA-10213: Updated mvn-shade-plugin to 3.5.1

- acceptance-tests/pom.xml
- pom.xml
- JIRA story: https://jira.cms.gov/browse/QPPA-10214
> QPPA-10214: Updates maven-jar-plugin to v3.4.2

- commons/pom.xml
- JIRA story https://jira.cms.gov/browse/QPPA-10215
> QPPA-10215: Updates download-maven-plugin to v2.0.0

- pom.xml
- JIRA story https://jira.cms.gov/browse/QPPA-10216
> QPPA-10216: Upgrade maven-javadoc-plugin from v3.1.1 to v3.11.2

- generate/pom.xml
- Fixes #10217
- JIRA story https://jira.cms.gov/browse/QPPA-10217
-
-
> feat: QPPA-10217 update maven-plugin-plugin

- commons/src/main/resources/measures-data.json
- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/CustomRequestLoggingFilter.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/HeaderRemovingRequestWrapper.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/config/RequestLoggingFilterConfig.java
- Fixes #10329.
- JIRA story https://jira.cms.gov/browse/QPPA-10329.
- Adds logic to remove sensitive data from logger
-
-
> QPPA-10329: Remove sensitive data from logger

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
- Fixes #_.
- JIRA story https://jira.cms.gov/browse/QPPA-10416
> QPPA-10416: Updates release version to v2024.2.12-RELEASE

- .github/workflows/sonarqube.yml
- sonar-project.properties
https://jira.cms.gov/browse/QPPA-10370
This pull request adds a SonarQube configuration YAML file to the repository. The purpose of this change is to introduce automated code quality analysis and static code inspection via SonarQube, helping to maintain and improve code quality standards in the project.
> QPPA-10370: add sonarqube yml

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- commons/src/main/resources/measures-data.json
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
- JIRA story https://jira.cms.gov/browse/QPPA-10498
> QPPA-10498: bump version number and updates measures data

- commons/src/main/java/gov/cms/qpp/conversion/model/validation/MeasureConfig.java
- commons/src/main/java/gov/cms/qpp/conversion/model/validation/Strata.java
- commons/src/main/java/gov/cms/qpp/conversion/model/validation/SubPopulation.java
- converter/src/main/java/gov/cms/qpp/conversion/Context.java
- converter/src/main/java/gov/cms/qpp/conversion/ConversionReport.java
- converter/src/main/java/gov/cms/qpp/conversion/Converter.java
- converter/src/main/java/gov/cms/qpp/conversion/correlation/model/Correlation.java
- converter/src/main/java/gov/cms/qpp/conversion/correlation/model/CorrelationConfig.java
- converter/src/main/java/gov/cms/qpp/conversion/correlation/model/PathCorrelation.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/JsonOutputEncoder.java
- converter/src/main/java/gov/cms/qpp/conversion/encode/JsonWrapper.java
- converter/src/main/java/gov/cms/qpp/conversion/model/DecodeData.java
- converter/src/main/java/gov/cms/qpp/conversion/model/Node.java
- converter/src/main/java/gov/cms/qpp/conversion/model/Registry.java
- converter/src/main/java/gov/cms/qpp/conversion/model/error/AllErrors.java
- converter/src/main/java/gov/cms/qpp/conversion/model/error/Detail.java
- converter/src/main/java/gov/cms/qpp/conversion/model/error/Error.java
- converter/src/main/java/gov/cms/qpp/conversion/model/error/TransformException.java
- converter/src/main/java/gov/cms/qpp/conversion/model/error/ValidationResult.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/ConvertResponse.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Details.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/ErrorMessage.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Metadata.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/PcfValidationInfoMap.java
- rest-api/src/main/java/gov/cms/qpp/conversion/api/model/Report.java
Fixes https://jira.cms.gov/browse/QPPA-10269
Fixes issues flagged by the SpotBugs plugin.
Returns defensive copies for internal collections/objects to improve code safety and immutability.
Adds or improves Javadoc comments.
Minor refactoring and better null handling.
No feature changes, just code quality improvements
Suppressions for specific SpotBugs warnings (e.g., @SuppressFBWarnings("EI_EXPOSE_REP")) were added where necessary.
> QPPA-10269: resolve spotbugs plugin issues

- .github/workflows/sonarqube.yml
- removes 'closed' from PR type list
> QPPA-0000: keeps sonarqube from running when PRs are closed

- acceptance-tests/pom.xml
- rest-api/pom.xml
- Fixes #QPPA-10545.
- JIRA story QPPA-10545.
-
-
> QPPA-10545: Resolve spring-webmvc

- pom.xml
- rest-api/pom.xml
- Fixes https://jira.cms.gov/browse/QPPA-10604
Upgrade spring-security-crypto to 6.3.8
> QPPA-10604: update org.springframework.security version

- rest-api/pom.xml
- JIRA story https://jira.cms.gov/browse/QPPA-10603.
- Updated tomcat version
> QPPA-10603: Updates tomcat version in rest api

- generate/pom.xml
- pom.xml
- rest-api/pom.xml
- JIRA story https://jira.cms.gov/browse/QPPA-10618
> QPPA-10618 updates spring security and spring framework

- Dockerfile
- DockerfileTest
> QPPA-0000: Prune sourcecode dockerfile

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
- JIRA story https://jira.cms.gov/browse/QPPA-10664
> QPPA-10664: Release v2025.07.31.01

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
- JIRA story https://jira.cms.gov/browse/QPPA-10689
> QPPA-10689: Updates pom files for new version

- acceptance-tests/pom.xml
- commandline/pom.xml
- commons/pom.xml
- converter/pom.xml
- generate-race-cpcplus/pom.xml
- generate/pom.xml
- pom.xml
- qrda3-update-measures/pom.xml
- rest-api/pom.xml
- test-commons/pom.xml
- test-coverage/pom.xml
> QPPA-10785: Deploy v2025.09.03.01

- .github/workflows/ci-build.yml
- Dockerfile
- commons/src/main/resources/measures-data.json
- converter/pom.xml
- pom.xml
- rest-api/pom.xml
> QPPA-10750: Expose javadoc functionality
